// Parity breadcrumbs:
// - none: Open Bitcoin-only support/infrastructure; no direct Bitcoin Knots source anchor identified.

use super::*;

#[test]
fn plist_content_contains_required_fields() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoind");
    let datadir = Path::new("/fake/datadir");

    // Act
    let content = generate_plist_content("org.open-bitcoin.node", binary, datadir, None, None);

    // Assert
    assert!(
        content.contains("<string>org.open-bitcoin.node</string>"),
        "missing label: {content}"
    );
    assert!(
        content.contains("<string>/fake/bin/open-bitcoind</string>"),
        "missing binary path: {content}"
    );
    assert!(
        !content.contains("<string>/fake/bin/open-bitcoin</string>"),
        "plist should not supervise operator binary: {content}"
    );
    assert!(
        content.contains("<string>-datadir=/fake/datadir</string>"),
        "missing daemon datadir arg: {content}"
    );
    assert!(
        !content.contains("<string>--datadir</string>"),
        "plist should not use operator CLI datadir flag: {content}"
    );
    assert!(
        content.contains("<true/>"),
        "missing KeepAlive or RunAtLoad: {content}"
    );
    assert!(
        content.contains("Generated by Open Bitcoin"),
        "missing comment header: {content}"
    );
}

#[test]
fn plist_content_includes_config_path_when_provided() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoind");
    let datadir = Path::new("/fake/datadir");
    let config = Path::new("/fake/config/open-bitcoin.jsonc");

    // Act
    let content =
        generate_plist_content("org.open-bitcoin.node", binary, datadir, Some(config), None);

    // Assert
    assert!(
        content.contains("<string>-openbitcoinconf=/fake/config/open-bitcoin.jsonc</string>"),
        "missing daemon config arg: {content}"
    );
    assert!(
        !content.contains("<string>--config</string>"),
        "plist should not use operator CLI config flag: {content}"
    );
}

#[test]
fn plist_content_includes_log_paths_when_provided() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoind");
    let datadir = Path::new("/fake/datadir");
    let log = Path::new("/fake/logs/open-bitcoin.log");

    // Act
    let content = generate_plist_content("org.open-bitcoin.node", binary, datadir, None, Some(log));

    // Assert
    assert!(
        content.contains("StandardOutPath"),
        "missing StandardOutPath: {content}"
    );
    assert!(
        content.contains("StandardErrorPath"),
        "missing StandardErrorPath: {content}"
    );
    assert!(
        content.contains("/fake/logs/open-bitcoin.log"),
        "missing log path: {content}"
    );
}

#[test]
fn service_log_path_from_log_dir_appends_default_file_name() {
    // Arrange
    let log_dir = Path::new("/fake/logs");

    // Act
    let maybe_log_path = service_log_path_from_log_dir(Some(log_dir));

    // Assert
    assert_eq!(
        maybe_log_path,
        Some(PathBuf::from("/fake/logs/open-bitcoin.log"))
    );
}

// --- Unit file generator tests ---

#[test]
fn unit_content_contains_required_fields() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoind");
    let datadir = Path::new("/fake/datadir");

    // Act
    let content = generate_unit_content(binary, datadir, None, None);

    // Assert
    assert!(content.contains("[Unit]"), "missing [Unit]: {content}");
    assert!(
        content.contains("[Service]"),
        "missing [Service]: {content}"
    );
    assert!(
        content.contains("[Install]"),
        "missing [Install]: {content}"
    );
    assert!(
        content.contains("ExecStart=\"/fake/bin/open-bitcoind\" \"-datadir=/fake/datadir\""),
        "missing ExecStart: {content}"
    );
    assert!(
        !content.contains("--datadir"),
        "unit should not use operator CLI datadir flag: {content}"
    );
    assert!(
        !content.contains("ExecStart=\"/fake/bin/open-bitcoin\""),
        "unit should not supervise operator binary: {content}"
    );
    assert!(
        content.contains("Restart=on-failure"),
        "missing Restart: {content}"
    );
    assert!(
        content.contains("WantedBy=default.target"),
        "missing WantedBy: {content}"
    );
    assert!(
        content.contains("# Generated by Open Bitcoin"),
        "missing comment header: {content}"
    );
}

#[test]
fn unit_content_includes_config_path_when_provided() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoind");
    let datadir = Path::new("/fake/datadir");
    let config = Path::new("/fake/config/open-bitcoin.jsonc");

    // Act
    let content = generate_unit_content(binary, datadir, Some(config), None);

    // Assert
    assert!(
        content.contains("\"-openbitcoinconf=/fake/config/open-bitcoin.jsonc\""),
        "missing daemon config arg: {content}"
    );
    assert!(
        !content.contains("--config"),
        "unit should not use operator CLI config flag: {content}"
    );
}

#[test]
fn unit_content_includes_log_path_when_provided() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoind");
    let datadir = Path::new("/fake/datadir");
    let log_path = Path::new("/fake/logs/open-bitcoin.log");

    // Act
    let content = generate_unit_content(binary, datadir, None, Some(log_path));

    // Assert
    assert!(
        content.contains("StandardOutput=append:/fake/logs/open-bitcoin.log"),
        "missing StandardOutput append path: {content}"
    );
    assert!(
        content.contains("StandardError=append:/fake/logs/open-bitcoin.log"),
        "missing StandardError append path: {content}"
    );
}

// --- FakeServiceManager tests ---

#[test]
fn fake_manager_install_records_call() {
    // Arrange
    let manager = FakeServiceManager::unmanaged();
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoind"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: true,
    };

    // Act
    let result = manager.install(&request);

    // Assert
    assert!(result.is_ok(), "install should succeed: {result:?}");
    let calls = manager.recorded_calls.borrow();
    assert_eq!(calls.len(), 1);
    assert_eq!(calls[0], FakeServiceCall::Install { apply: true });
}

#[test]
fn fake_manager_status_returns_configured_state() {
    // Arrange
    let snapshot = ServiceStateSnapshot {
        state: ServiceLifecycleState::Unmanaged,
        maybe_enabled: Some(false),
        maybe_service_file_path: None,
        maybe_manager_diagnostics: None,
        maybe_log_path: None,
        maybe_log_path_unavailable_reason: Some("service not installed".to_string()),
        maybe_data_dir: None,
        maybe_data_dir_unavailable_reason: Some("service not installed".to_string()),
    };
    let manager = FakeServiceManager::new(snapshot.clone());

    // Act
    let result = manager.status();

    // Assert
    assert!(result.is_ok());
    assert_eq!(result.unwrap(), snapshot);
    let calls = manager.recorded_calls.borrow();
    assert_eq!(calls.len(), 1);
    assert_eq!(calls[0], FakeServiceCall::Status);
}

// --- ServiceError display tests ---

#[test]
fn service_error_unsupported_platform_displays_reason() {
    // Arrange
    let error = ServiceError::UnsupportedPlatform {
        reason: "Windows is not supported".to_string(),
    };

    // Act
    let display = error.to_string();

    // Assert
    assert!(
        display.contains("Windows is not supported"),
        "missing reason: {display}"
    );
    assert!(
        display.contains("unsupported platform"),
        "missing prefix: {display}"
    );
}

#[test]
fn service_error_already_installed_displays_path() {
    // Arrange
    let path = PathBuf::from("/home/user/Library/LaunchAgents/org.open-bitcoin.node.plist");
    let error = ServiceError::AlreadyInstalled { path: path.clone() };

    // Act
    let display = error.to_string();

    // Assert
    assert!(
        display.contains(path.to_str().unwrap()),
        "missing path: {display}"
    );
    assert!(
        display.contains("already installed"),
        "missing prefix: {display}"
    );
}

#[test]
fn service_error_not_installed_points_to_preview_and_apply() {
    // Arrange
    let error = ServiceError::NotInstalled;

    // Act
    let display = error.to_string();

    // Assert
    assert!(
        display.contains("open-bitcoin service install"),
        "missing preview command: {display}"
    );
    assert!(
        display.contains("--apply"),
        "missing apply guidance: {display}"
    );
    assert!(
        !display.contains("--dry-run"),
        "stale dry-run hint: {display}"
    );
}

// --- LaunchdAdapter dry-run isolation tests ---

#[test]
fn launchd_install_dry_run_does_not_write_file() {
    // Arrange
    let test_dir = TestDirectory::new("launchd-dry-run");
    let home_dir = test_dir.path.clone();
    let adapter = LaunchdAdapter::new(home_dir.clone());
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoind"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: false,
    };

    // Act
    let result = adapter.install(&request);

    // Assert
    assert!(result.is_ok(), "dry-run should succeed: {result:?}");
    let outcome = result.unwrap();
    assert!(outcome.dry_run, "outcome should be dry_run=true");
    let plist_path = home_dir
        .join("Library")
        .join("LaunchAgents")
        .join("org.open-bitcoin.node.plist");
    assert!(
        !plist_path.exists(),
        "plist file must NOT exist after dry-run"
    );
}

#[test]
fn launchd_install_dry_run_lists_enable_and_bootstrap_commands() {
    // Arrange
    let test_dir = TestDirectory::new("launchd-dry-run-commands");
    let adapter = LaunchdAdapter::new(test_dir.path.clone());
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoind"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: false,
    };

    // Act
    let outcome = adapter.install(&request).expect("launchd dry-run install");

    // Assert
    assert_eq!(outcome.commands_that_would_run.len(), 2);
    assert!(
        outcome.commands_that_would_run[0].starts_with("launchctl enable gui/"),
        "missing launchctl enable preview: {:?}",
        outcome.commands_that_would_run
    );
    assert!(
        outcome.commands_that_would_run[1].starts_with("launchctl bootstrap gui/"),
        "missing launchctl bootstrap preview: {:?}",
        outcome.commands_that_would_run
    );
}

// --- SystemdAdapter dry-run isolation tests ---

#[test]
fn systemd_install_dry_run_does_not_write_file() {
    // Arrange
    let test_dir = TestDirectory::new("systemd-dry-run");
    let home_dir = test_dir.path.clone();
    let adapter = SystemdAdapter::new(home_dir.clone());
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoind"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: false,
    };

    // Act
    let result = adapter.install(&request);

    // Assert
    assert!(result.is_ok(), "dry-run should succeed: {result:?}");
    let outcome = result.unwrap();
    assert!(outcome.dry_run, "outcome should be dry_run=true");
    let unit_path = home_dir
        .join(".config")
        .join("systemd")
        .join("user")
        .join("open-bitcoin-node.service");
    assert!(
        !unit_path.exists(),
        "unit file must NOT exist after dry-run"
    );
}

#[test]
fn systemd_install_dry_run_lists_reload_and_enable_commands() {
    // Arrange
    let test_dir = TestDirectory::new("systemd-dry-run-commands");
    let adapter = SystemdAdapter::new(test_dir.path.clone());
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoind"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: false,
    };

    // Act
    let outcome = adapter.install(&request).expect("systemd dry-run install");

    // Assert
    assert_eq!(
        outcome.commands_that_would_run,
        vec![
            "systemctl --user daemon-reload".to_string(),
            "systemctl --user enable open-bitcoin-node.service".to_string(),
        ]
    );
}

#[test]
fn launchd_disabled_services_parser_detects_enabled_and_disabled_entries() {
    // Arrange
    let disabled_output = r#"
{
    "org.open-bitcoin.node" => true
}
"#;
    let enabled_output = r#"
{
    "org.open-bitcoin.node" => false
}
"#;

    // Act / Assert
    assert_eq!(
        parse_launchd_disabled_services(disabled_output, "org.open-bitcoin.node"),
        Some(false)
    );
    assert_eq!(
        parse_launchd_disabled_services(enabled_output, "org.open-bitcoin.node"),
        Some(true)
    );
}

#[test]
fn launchd_log_path_parser_reads_standard_out_path() {
    // Arrange
    let plist = r#"
<dict>
    <key>StandardOutPath</key>
    <string>/fake/logs/open-bitcoin.log</string>
    <key>StandardErrorPath</key>
    <string>/fake/logs/open-bitcoin.log</string>
</dict>
"#;

    // Act
    let maybe_log_path = parse_launchd_log_path(plist);

    // Assert
    assert_eq!(
        maybe_log_path,
        Some(PathBuf::from("/fake/logs/open-bitcoin.log"))
    );
}
