export const NODE = "packages/open-bitcoin-node/src/";
export const CORE = "packages/open-bitcoin-chainstate/src/";
export const RPC = "packages/open-bitcoin-rpc/src/";
const OWNER = NODE + "storage/fjall_store/filters/ownership.rs";
const PUB = NODE + "storage/fjall_store/filters/publication.rs";
const LIFE = NODE + "storage/fjall_store/filters/lifecycle.rs";
const PRUNE = NODE + "storage/fjall_store/prune.rs";
const AUTO = NODE + "network/runtime_authority/automatic_prune.rs";
const RT = NODE + "sync/tests/filter_index/";
const OT = NODE + "storage/fjall_store/filters/tests/";
export type Contract = { threat: string; file: string; symbol: string; anchors: readonly string[];
  testFile: string; testName: string };
const contract = (id: number, file: string, symbol: string, anchors: string[],
  testFile: string, testName: string): Contract => ({
    threat: `T-156-${String(id).padStart(2, "0")}`, file, symbol, anchors, testFile, testName,
  });
/** Each threat links narrow production code to a real named behavioral test. */
export const CONTRACTS: Contract[] = [
  contract(1, NODE + "storage/filter_index/ownership.rs", "decode_owner",
    ["if bytes.len() != OWNER_LENGTH", "cursor.version()?", "cursor.finish()?", "match mode"],
    NODE + "storage/filter_index/tests.rs", "owner_refuses_every_truncation_and_trailing_bytes_as_corruption"),
  contract(2, CORE + "filter_index/lifecycle.rs", "check_work",
    ["self != work.expected", "fence_height != work.fence_height", "fence_hash != work.fence_hash"],
    CORE + "filter_index/tests/lifecycle.rs", "same_generation_newer_checkpoint_refuses_old_work"),
  contract(3, CORE + "filter_index/lifecycle.rs", "maybe_from_artifacts",
    ["maybe_lifecycle.is_some()", "has_records", "has_projection", "IndexGeneration::new(0)", "IndexLifecycle::Disabled"],
    CORE + "filter_index/tests/lifecycle.rs", "legacy_absent_requires_all_artifacts_absent"),
  contract(4, PUB, "persist_basic_filter_records",
    ["self.check_basic_filter_work_guarded(work, fence, &control)?;", "self.prepare_basic_filter_records(records)?"],
    OT + "ownership.rs", "filter_index_same_generation_old_frontier_refuses_rows_and_checkpoint_after_reopen"),
  contract(5, PUB, "publish_basic_filter_checkpoint_guarded",
    ["self.verify_basic_filter_fence(fence)?;", "self.validate_basic_filter_records()?;", "self.scan_basic_filter_checkpoint(",
      "self.prepare_basic_filter_projection(", "SyncAll", "codec::STATE_KEY", "PRUNE_LOCKS_KEY", "self.finish_basic_filter_batch("],
    RT + "faults.rs", "filter_index_production_reopens_every_record_and_checkpoint_fault_boundary"),
  contract(6, NODE + "storage/fjall_store/filters/startup.rs", "recover_basic_filter_index",
    ["self.filter_publication_guard()?", "IndexLifecycle::Disabled", ".check_prune_intent(intent.height)",
      "self.materialize_basic_filter_owner_guarded("],
    RT + "prune_faults.rs", "filter_index_runtime_constructor_materializes_legacy_nonempty_prefix_durably"),
  contract(7, PUB, "finish_basic_filter_batch",
    ["batch.commit()", "control.poisoned = true", "after_commit_fault(control)"],
    RT + "faults.rs", "filter_index_production_after_record_commit_error_retains_ahead_rows_without_cursor"),
  contract(8, LIFE, "disable_basic_filter_index",
    ["owner.lifecycle().disable()", "codec::ownership::encode_owner(disabled)", "self.finish_basic_filter_batch(",
      "locks.retain(|lock| lock.name != BASIC_INDEX_PRUNE_LOCK)", "PRUNE_LOCKS_KEY", "self.finish_basic_filter_batch("],
    RT + "lifecycle.rs", "filter_index_production_host_disable_enable_rejects_old_work_and_preserves_history"),
  contract(9, LIFE, "preflight_basic_filter_history",
    ["let IndexInputProtection::FromHeight(first)", "self", ".load_block(", "if height == 0", ".load_undo(",
      "BasicFilterInputs::from_historical("],
    RT + "lifecycle.rs", "filter_index_production_reenable_missing_body_or_undo_keeps_disabled_prefix"),
  contract(10, LIFE, "enable_basic_filter_index",
    ["self.verify_basic_filter_fence(fence)?", "self.preflight_basic_filter_history(", "self.initialize_basic_filter_state_guarded("],
    RT + "prune_faults.rs", "filter_index_runtime_enable_faults_reopen_only_committed_ownership"),
  contract(11, NODE + "network/runtime_authority/filter_index.rs", "enable_basic_filter_index",
    ["self.mutate(|network|", "network.chainstate().store().inner()", "VerifiedChainstateFence::new(",
      "store.enable_basic_filter_index(&fence)"],
    RT + "lifecycle.rs", "filter_index_production_absent_host_activation_and_genesis_needs_no_undo"),
  contract(12, NODE + "network/runtime_authority/prune_flush.rs", "clear_prune_lock",
    ["refuse_reserved_name(name)?;", "self.mutate(", "return Ok(false)"],
    RPC + "dispatch/prune/tests/ownership.rs", "prune_dispatch_reserved_refuses_absent_active_and_disabled_owners"),
  contract(13, NODE + "storage/fjall_store/prune/records.rs", "sync_prune_locks",
    ["self.filter_publication_guard()?", "self.maybe_basic_filter_owner_guarded(&control)?", "self.load_prune_locks()?",
      "if maybe_current != maybe_proposed", "self.sync_block_index_value("],
    NODE + "storage/fjall_store/tests/prune_records.rs", "prune_map_requires_exact_reserved_entry_and_preserves_unrelated_updates"),
  contract(14, RPC + "http.rs", "handle_http_request",
    ["!authorized(headers, &state.auth)", "return unauthorized_response()", "serde_json::from_slice"],
    RPC + "http/tests/prune_ownership.rs", "prune_http_authentication_precedes_reserved_dispatch_and_parsing"),
  contract(15, PRUNE, "commit_paired_delete_observing",
    ["self.filter_publication_guard()?", "self.check_prune_candidate_guarded(", "self.with_payload_mutation(",
      "self.commit_paired_delete_guarded("],
    NODE + "storage/fjall_store/tests/prune_unlink/protection.rs", "prune_owned_forged_height_refuses_direct_and_standalone_intent_in_both_modes"),
  contract(16, NODE + "chainstate/flush_lifecycle/prune_apply.rs", "unlink_classified_height",
    ["sink.load_prune_protection()?", "owner.maybe_effective_protection()", "current_locks.extend_from_slice(locks)",
      "classify_protected_prune_height(", "sink.commit_paired_unlink("],
    RT + "prune_coordination.rs", "filter_index_clone_change_after_application_snapshot_reaches_final_concrete_refusal"),
  contract(17, PRUNE, "maybe_owned_prune_ancestry",
    ["!view.head_blocks()", "view.best_block()", "VerifiedChainstateFence::new(", "saved.fence_height()",
      "saved.fence_hash()", "endpoint.block_hash()", "endpoint.parent_hash()"],
    NODE + "storage/fjall_store/tests/prune_unlink/protection.rs", "prune_owned_current_coins_must_be_recovered_and_match_metadata"),
  contract(18, NODE + "chainstate/flush_lifecycle/prune_apply.rs", "apply_prune_plan",
    ["unlink_classified_height(", "if let HeightPruneOutcome::DeletedLiveMate", "on_deleted(block_hash)",
      "sink.record_successful_prune_batch(&deleted_heights)?"],
    NODE + "chainstate/flush_lifecycle/prune_apply/tests.rs", "later_candidate_failure_preserves_only_cleanup_earned_by_live_receipt"),
  contract(19, AUTO, "prepare",
    ["store.load_prune_protection()?", "state.maybe_last_measured_protection_identity.as_ref() != Some(&protection)",
      "state.invalidate()", "state.maybe_completed_key.as_ref() == Some(&key)", "mode == FlushMode::Periodic"],
    NODE + "network/runtime_authority/automatic_prune/tests/protection.rs",
    "automatic_prune_owner_generation_lifecycle_and_fence_changes_invalidate_both_gates"),
  contract(20, OWNER, "check_basic_filter_work_guarded",
    ["Arc::ptr_eq(&work.publication, &self.filter_publication)", "self.maybe_basic_filter_owner_guarded(control)?",
      ".check_work(work.identity", "self.verify_basic_filter_fence(fence)"],
    NODE + "network/runtime_authority/automatic_prune/tests/protection.rs",
    "automatic_prune_real_clone_lifecycle_and_checkpoint_changes_are_visible_same_second"),
  contract(21, AUTO, "prepare",
    [".retain(|height, _| !protection.protects_height(*height))", "current_usage_bytes: usage.current_usage_bytes"],
    NODE + "network/runtime_authority/automatic_prune/tests/protection.rs",
    "automatic_prune_direct_low_inputs_are_not_candidate_budget_or_forced_checkpoint"),
  contract(22, PRUNE, "resume_prune_intent",
    ["store.filter_publication_guard()", ".maybe_basic_filter_owner_guarded(&control)", "load_resume_intent(store)?",
      "check_owned_prune_candidate(", "current_locks.extend_from_slice(locks)", "finish_intent(store, intent)"],
    RT + "prune_coordination.rs", "filter_index_runtime_direct_and_resume_required_genesis_and_height_one_refuse"),
  contract(23, AUTO, "flush",
    ["prepare(", "FlushMode::Always", "flush_and_evict_pruned_blocks("],
    RPC + "bin/open_bitcoind/tests/automatic_prune/index_protection.rs",
    "index_protection_ordinary_legal_target_retains_then_deletes_only_after_disable"),
  contract(24, RPC + "context/prune.rs", "clear_named_prune_lock",
    ["refuse_reserved_name(name)?", ".clear_prune_lock(name)"],
    RPC + "http/tests/prune_ownership.rs", "prune_http_ordinary_authenticated_crud_persists_with_reserved_owner"),
  contract(25, LIFE, "preflight_basic_filter_history",
    ["HistoricalBlockUndo", "BasicFilterInputs::from_historical("],
    RT + "recovery.rs", "filter_index_production_validated_ahead_records_do_not_mint_cursor"),
];

export const REGISTRATIONS: [string, string[]][] = [
  [CORE + "filter_index.rs", ["pub mod lifecycle;"]],
  [CORE + "filter_index/tests.rs", ["mod lifecycle;"]],
  [NODE + "storage/filter_index.rs", ["mod ownership;", "mod tests;"]],
  [NODE + "storage/fjall_store/filters.rs", ["mod ownership;", "mod lifecycle;", "mod publication;", "mod tests;"]],
  [NODE + "storage/fjall_store/filters/tests.rs", ["mod ownership;", "mod lifecycle;"]],
  [NODE + "sync/tests.rs", ["mod filter_index;"]],
  [NODE + "sync/tests/filter_index.rs", ["mod prune_coordination;", "mod prune_faults;", "mod lifecycle;", "mod faults;", "mod recovery;"]],
  [NODE + "storage/fjall_store/tests.rs", ["mod prune_records;", "mod prune_unlink;"]],
  [NODE + "storage/fjall_store/tests/prune_unlink.rs", ["mod protection;"]],
  [NODE + "chainstate/flush_lifecycle/prune_apply.rs", ["mod tests;"]],
  [NODE + "network/runtime_authority/automatic_prune.rs", ["mod tests;"]],
  [NODE + "network/runtime_authority/automatic_prune/tests.rs", ["mod protection;"]],
  [RPC + "dispatch/prune/tests.rs", ["mod ownership;"]],
  [RPC + "http/tests.rs", ["mod prune_ownership;"]],
  [RPC + "bin/open_bitcoind/tests/automatic_prune.rs", ["mod index_protection;"]],
];
