//! Fixed-width Bitcoin hash primitives and semantic wrapper types.
//!
//! [`Hash32`] is the generic 32-byte storage type used by this module. The
//! wrapper types generated by [`define_hash_wrapper!`] add semantic meaning on
//! top of the same byte representation so later code cannot accidentally mix
//! transaction identifiers, witness-aware identifiers, block hashes, and
//! merkle roots.
//!
//! # Examples
//!
//! ```
//! use open_bitcoin_primitives::{Hash32, Txid, Wtxid};
//!
//! let raw = [0x11_u8; 32];
//! let txid = Txid::from_byte_array(raw);
//! let parsed_wtxid = Wtxid::from_slice(&raw).expect("32-byte hash");
//! let generic_hash = Hash32::from(txid);
//!
//! assert_eq!(parsed_wtxid.to_byte_array(), raw);
//! assert_eq!(generic_hash.to_byte_array(), raw);
//! ```

use core::fmt;

/// Error returned when a byte slice does not match the required fixed hash
/// width.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HashLengthError {
    pub expected: usize,
    pub actual: usize,
}

impl fmt::Display for HashLengthError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "invalid hash length: expected {}, got {}",
            self.expected, self.actual
        )
    }
}

impl std::error::Error for HashLengthError {}

/// Generic fixed-width 32-byte storage for Bitcoin hash-like values.
///
/// This type preserves the raw bytes only. Use the semantic wrappers generated
/// by [`define_hash_wrapper!`] when the hash role matters at the type level.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
pub struct Hash32([u8; 32]);

impl Hash32 {
    /// Required byte width for every value stored in this type.
    pub const LEN: usize = 32;

    /// Wrap an already validated 32-byte array.
    pub const fn from_byte_array(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Parse a borrowed byte slice into a fixed-width hash value.
    pub fn from_slice(bytes: &[u8]) -> Result<Self, HashLengthError> {
        let Ok(array) = <[u8; 32]>::try_from(bytes) else {
            return Err(HashLengthError {
                expected: Self::LEN,
                actual: bytes.len(),
            });
        };

        Ok(Self(array))
    }

    /// Borrow the underlying bytes without changing their semantic meaning.
    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }

    /// Return the underlying bytes by value.
    pub const fn to_byte_array(self) -> [u8; 32] {
        self.0
    }
}

/// Define a semantic wrapper around [`Hash32`] without duplicating the shared
/// constructor and conversion boilerplate.
///
/// The generated type is a newtype over [`Hash32`] and exposes:
/// - `from_byte_array` for already validated `[u8; 32]` inputs
/// - `from_slice` for borrowed byte parsing with [`HashLengthError`]
/// - `as_bytes` and `to_byte_array` for explicit byte access
/// - `From<Hash32>` and `From<$name> for Hash32` conversions
///
/// The wrapper exists to keep distinct Bitcoin hash roles type-safe while still
/// reusing a single fixed-width storage implementation.
macro_rules! define_hash_wrapper {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
        pub struct $name(Hash32);

        impl $name {
            /// Wrap an already validated 32-byte array in this semantic hash type.
            pub const fn from_byte_array(bytes: [u8; 32]) -> Self {
                Self(Hash32::from_byte_array(bytes))
            }

            /// Parse a borrowed byte slice into this semantic hash type.
            pub fn from_slice(bytes: &[u8]) -> Result<Self, HashLengthError> {
                Ok(Self(Hash32::from_slice(bytes)?))
            }

            /// Borrow the underlying 32-byte representation.
            pub fn as_bytes(&self) -> &[u8; 32] {
                self.0.as_bytes()
            }

            /// Return the underlying 32-byte representation by value.
            pub const fn to_byte_array(self) -> [u8; 32] {
                self.0.to_byte_array()
            }
        }

        impl From<Hash32> for $name {
            fn from(value: Hash32) -> Self {
                Self(value)
            }
        }

        impl From<$name> for Hash32 {
            fn from(value: $name) -> Self {
                value.0
            }
        }
    };
}

define_hash_wrapper!(
    /// Non-witness transaction identifier.
    ///
    /// Use this when a value is specifically the legacy transaction ID, not a
    /// generic hash and not the witness-aware transaction identifier.
    Txid
);
define_hash_wrapper!(
    /// Witness-aware transaction identifier.
    ///
    /// Use this when the identifier must preserve witness serialization
    /// semantics instead of the legacy non-witness transaction ID.
    Wtxid
);
define_hash_wrapper!(
    /// Block identifier for a serialized block header.
    BlockHash
);
define_hash_wrapper!(
    /// Merkle-root hash committed into a block header.
    MerkleRoot
);

#[cfg(test)]
mod tests {
    use super::{BlockHash, Hash32, HashLengthError, MerkleRoot, Txid, Wtxid};

    #[test]
    fn hash32_from_slice_requires_exact_length() {
        let valid = [7_u8; 32];
        assert_eq!(
            Hash32::from_slice(&valid),
            Ok(Hash32::from_byte_array(valid))
        );
        assert_eq!(
            Hash32::from_slice(&valid[..31]),
            Err(HashLengthError {
                expected: 32,
                actual: 31,
            }),
        );
    }

    #[test]
    fn wrappers_preserve_underlying_bytes() {
        let bytes = [9_u8; 32];
        let txid = Txid::from_byte_array(bytes);
        let wtxid = Wtxid::from_slice(&bytes).expect("valid wtxid bytes");
        let block_hash = BlockHash::from(Hash32::from_byte_array(bytes));
        let merkle_root = MerkleRoot::from_slice(&bytes).expect("valid merkle root");

        assert_eq!(txid.as_bytes(), &bytes);
        assert_eq!(txid.to_byte_array(), bytes);
        assert_eq!(wtxid.as_bytes(), &bytes);
        assert_eq!(Hash32::from(block_hash).to_byte_array(), bytes);
        assert_eq!(Hash32::from(merkle_root).to_byte_array(), bytes);
    }

    #[test]
    fn hash_length_error_display_is_descriptive() {
        let error = HashLengthError {
            expected: 32,
            actual: 12,
        };

        assert_eq!(
            error.to_string(),
            "invalid hash length: expected 32, got 12",
        );
    }
}
