// Parity breadcrumbs:
// - none: Open Bitcoin-only support/infrastructure; no direct Bitcoin Knots source anchor identified.

//! macOS launchd service adapter for the Open Bitcoin node.
//!
//! `generate_plist_content()` is a pure function exercised in tests without filesystem or
//! subprocess access. `LaunchdAdapter` wraps effectful operations (file writes and
//! `launchctl` invocations) behind the `ServiceManager` trait.

use std::path::{Path, PathBuf};

use super::{
    ServiceCommandOutcome, ServiceDisableRequest, ServiceEnableRequest, ServiceError,
    ServiceInstallRequest, ServiceLifecycleState, ServiceManager, ServiceStateSnapshot,
    ServiceUninstallRequest,
};

/// launchd label for the Open Bitcoin node service.
pub const OPEN_BITCOIN_LAUNCHD_LABEL: &str = "org.open-bitcoin.node";

/// launchd plist filename for the Open Bitcoin node service.
pub const OPEN_BITCOIN_LAUNCHD_FILE_NAME: &str = "org.open-bitcoin.node.plist";

/// Escape XML special characters in a string for safe embedding in plist `<string>` elements.
fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Generate a macOS launchd plist XML string for the Open Bitcoin node.
///
/// This is a pure function — no filesystem access or subprocess calls occur here.
pub fn generate_plist_content(
    label: &str,
    binary_path: &Path,
    data_dir: &Path,
    maybe_config_path: Option<&Path>,
    maybe_log_path: Option<&Path>,
) -> String {
    let binary_str = xml_escape(&binary_path.display().to_string());
    let data_dir_str = xml_escape(&data_dir.display().to_string());

    let mut config_args = String::new();
    if let Some(config_path) = maybe_config_path {
        let config_str = xml_escape(&config_path.display().to_string());
        config_args =
            format!("\n        <string>--config</string>\n        <string>{config_str}</string>",);
    }

    let mut log_keys = String::new();
    if let Some(log_path) = maybe_log_path {
        let log_str = xml_escape(&log_path.display().to_string());
        log_keys = format!(
            "\n    <key>StandardOutPath</key>\n    <string>{log_str}</string>\n    <key>StandardErrorPath</key>\n    <string>{log_str}</string>"
        );
    }

    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by Open Bitcoin. Do not edit manually. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>{binary_str}</string>
        <string>--datadir</string>
        <string>{data_dir_str}</string>{config_args}
    </array>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>{log_keys}
</dict>
</plist>
"#
    )
}

/// macOS launchd service adapter.
///
/// Wraps plist file writes and `launchctl` invocations. Construct via `LaunchdAdapter::new()`;
/// inject into CLI routes via the `ServiceManager` trait.
pub struct LaunchdAdapter {
    home_dir: PathBuf,
}

impl LaunchdAdapter {
    pub fn new(home_dir: PathBuf) -> Self {
        Self { home_dir }
    }

    fn launch_agents_dir(&self) -> PathBuf {
        self.home_dir.join("Library").join("LaunchAgents")
    }

    fn plist_path(&self) -> PathBuf {
        self.launch_agents_dir()
            .join(OPEN_BITCOIN_LAUNCHD_FILE_NAME)
    }

    /// Retrieves the current user ID using the `id -u` command.
    fn uid() -> u32 {
        std::process::Command::new("id")
            .arg("-u")
            .output()
            .ok()
            .and_then(|out| String::from_utf8(out.stdout).ok())
            .and_then(|s| s.trim().parse::<u32>().ok())
            .unwrap_or(501) // fallback: typical first macOS user UID
    }
}

impl ServiceManager for LaunchdAdapter {
    fn install(
        &self,
        request: &ServiceInstallRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let plist_path = self.plist_path();
        let plist_content = generate_plist_content(
            OPEN_BITCOIN_LAUNCHD_LABEL,
            &request.binary_path,
            &request.data_dir,
            request.maybe_config_path.as_deref(),
            request.maybe_log_path.as_deref(),
        );
        let uid = Self::uid();
        let bootstrap_cmd = format!("launchctl bootstrap gui/{uid} {}", plist_path.display());

        if !request.apply {
            return Ok(ServiceCommandOutcome {
                dry_run: true,
                description: format!("Would write plist to {}", plist_path.display()),
                maybe_file_path: Some(plist_path),
                maybe_file_content: Some(plist_content),
                commands_that_would_run: vec![bootstrap_cmd],
            });
        }

        // apply=true: check for existing file before writing
        if plist_path.exists() {
            return Err(ServiceError::AlreadyInstalled { path: plist_path });
        }

        // Ensure the LaunchAgents directory exists
        if let Err(cause) = std::fs::create_dir_all(self.launch_agents_dir()) {
            return Err(ServiceError::WriteFailure {
                path: self.launch_agents_dir(),
                cause: cause.to_string(),
            });
        }

        std::fs::write(&plist_path, &plist_content).map_err(|cause| {
            ServiceError::WriteFailure {
                path: plist_path.clone(),
                cause: cause.to_string(),
            }
        })?;

        Ok(ServiceCommandOutcome {
            dry_run: false,
            description: format!("Wrote plist to {}", plist_path.display()),
            maybe_file_path: Some(plist_path),
            maybe_file_content: Some(plist_content),
            commands_that_would_run: vec![bootstrap_cmd],
        })
    }

    fn uninstall(
        &self,
        request: &ServiceUninstallRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let plist_path = self.plist_path();
        let uid = Self::uid();
        let bootout_cmd = format!("launchctl bootout gui/{uid}/{OPEN_BITCOIN_LAUNCHD_LABEL}");

        if !plist_path.exists() {
            return Err(ServiceError::NotInstalled);
        }

        if !request.apply {
            return Ok(ServiceCommandOutcome {
                dry_run: true,
                description: format!("Would remove plist at {}", plist_path.display()),
                maybe_file_path: Some(plist_path),
                maybe_file_content: None,
                commands_that_would_run: vec![bootout_cmd],
            });
        }

        // apply=true: run bootout then remove file
        let output = std::process::Command::new("launchctl")
            .args([
                "bootout",
                &format!("gui/{uid}/{OPEN_BITCOIN_LAUNCHD_LABEL}"),
            ])
            .output()
            .map_err(|cause| ServiceError::ManagerCommandFailed {
                exit_code: -1,
                stderr: cause.to_string(),
            })?;

        if !output.status.success() {
            let exit_code = output.status.code().unwrap_or(-1);
            let stderr = String::from_utf8_lossy(&output.stderr).to_string();
            // Exit code 36 means "operation not permitted" (service not loaded) — treat as non-fatal
            if exit_code != 36 {
                return Err(ServiceError::ManagerCommandFailed { exit_code, stderr });
            }
        }

        std::fs::remove_file(&plist_path).map_err(|cause| ServiceError::WriteFailure {
            path: plist_path.clone(),
            cause: cause.to_string(),
        })?;

        Ok(ServiceCommandOutcome {
            dry_run: false,
            description: format!("Removed plist at {}", plist_path.display()),
            maybe_file_path: Some(plist_path),
            maybe_file_content: None,
            commands_that_would_run: vec![bootout_cmd],
        })
    }

    fn enable(
        &self,
        request: &ServiceEnableRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let uid = Self::uid();
        let enable_cmd = format!("launchctl enable gui/{uid}/{OPEN_BITCOIN_LAUNCHD_LABEL}");

        let _ = request;

        let output = std::process::Command::new("launchctl")
            .args(["enable", &format!("gui/{uid}/{OPEN_BITCOIN_LAUNCHD_LABEL}")])
            .output()
            .map_err(|cause| ServiceError::ManagerCommandFailed {
                exit_code: -1,
                stderr: cause.to_string(),
            })?;

        if !output.status.success() {
            let exit_code = output.status.code().unwrap_or(-1);
            let stderr = String::from_utf8_lossy(&output.stderr).to_string();
            return Err(ServiceError::ManagerCommandFailed { exit_code, stderr });
        }

        Ok(ServiceCommandOutcome {
            dry_run: false,
            description: "Enabled service to start at login".to_string(),
            maybe_file_path: None,
            maybe_file_content: None,
            commands_that_would_run: vec![enable_cmd],
        })
    }

    fn disable(
        &self,
        request: &ServiceDisableRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let uid = Self::uid();
        let disable_cmd = format!("launchctl disable gui/{uid}/{OPEN_BITCOIN_LAUNCHD_LABEL}");

        let _ = request;

        let output = std::process::Command::new("launchctl")
            .args([
                "disable",
                &format!("gui/{uid}/{OPEN_BITCOIN_LAUNCHD_LABEL}"),
            ])
            .output()
            .map_err(|cause| ServiceError::ManagerCommandFailed {
                exit_code: -1,
                stderr: cause.to_string(),
            })?;

        if !output.status.success() {
            let exit_code = output.status.code().unwrap_or(-1);
            let stderr = String::from_utf8_lossy(&output.stderr).to_string();
            return Err(ServiceError::ManagerCommandFailed { exit_code, stderr });
        }

        Ok(ServiceCommandOutcome {
            dry_run: false,
            description: "Disabled service from starting at login".to_string(),
            maybe_file_path: None,
            maybe_file_content: None,
            commands_that_would_run: vec![disable_cmd],
        })
    }

    fn status(&self) -> Result<ServiceStateSnapshot, ServiceError> {
        let plist_path = self.plist_path();

        // If no plist file exists, it's unmanaged
        if !plist_path.exists() {
            return Ok(ServiceStateSnapshot {
                state: ServiceLifecycleState::Unmanaged,
                maybe_service_file_path: None,
                maybe_manager_diagnostics: Some(
                    "unmanaged — run `open-bitcoin service install --dry-run` to see what would be created".to_string()
                ),
                maybe_log_path: None,
            });
        }

        // Query launchd for the current state
        let output = std::process::Command::new("launchctl")
            .args(["list", OPEN_BITCOIN_LAUNCHD_LABEL])
            .output();

        let Ok(output) = output else {
            return Ok(ServiceStateSnapshot {
                state: ServiceLifecycleState::Installed,
                maybe_service_file_path: Some(plist_path),
                maybe_manager_diagnostics: Some("launchctl not available".to_string()),
                maybe_log_path: None,
            });
        };

        // Exit code 113 = service not registered with launchd
        if output.status.code() == Some(113) {
            return Ok(ServiceStateSnapshot {
                state: ServiceLifecycleState::Installed,
                maybe_service_file_path: Some(plist_path),
                maybe_manager_diagnostics: Some(
                    "service not registered with launchd (not bootstrapped)".to_string(),
                ),
                maybe_log_path: None,
            });
        }

        let stdout = String::from_utf8_lossy(&output.stdout).to_string();
        let state = if stdout.contains("\"PID\" = ") {
            ServiceLifecycleState::Running
        } else if stdout.contains("\"LastExitStatus\" = 0;") {
            ServiceLifecycleState::Stopped
        } else if output.status.success() {
            // Loaded but last exit was non-zero
            ServiceLifecycleState::Failed
        } else {
            ServiceLifecycleState::Installed
        };

        Ok(ServiceStateSnapshot {
            state,
            maybe_service_file_path: Some(plist_path),
            maybe_manager_diagnostics: if stdout.is_empty() {
                None
            } else {
                Some(stdout)
            },
            maybe_log_path: None,
        })
    }
}
