// Parity breadcrumbs:
// - none: Open Bitcoin-only support/infrastructure; no direct Bitcoin Knots source anchor identified.

//! macOS launchd service adapter and plist content generator for Open Bitcoin.

use std::path::{Path, PathBuf};

use super::{
    ServiceCommandOutcome, ServiceDisableRequest, ServiceEnableRequest, ServiceError,
    ServiceInstallRequest, ServiceLifecycleState, ServiceManager, ServiceStateSnapshot,
    ServiceUninstallRequest,
};

/// launchd service label for the Open Bitcoin node.
pub const OPEN_BITCOIN_LAUNCHD_LABEL: &str = "org.open-bitcoin.node";
/// Plist file name for the Open Bitcoin launchd service.
pub const OPEN_BITCOIN_LAUNCHD_FILE_NAME: &str = "org.open-bitcoin.node.plist";

/// Generate plist XML content for the Open Bitcoin launchd service.
///
/// Returns a complete Apple Property List XML string. Does not perform any I/O.
pub fn generate_plist_content(
    label: &str,
    binary_path: &Path,
    data_dir: &Path,
    maybe_config_path: Option<&Path>,
    maybe_log_path: Option<&Path>,
) -> String {
    let mut args = format!(
        "        <string>{binary}</string>\n        <string>--datadir</string>\n        <string>{datadir}</string>\n",
        binary = binary_path.display(),
        datadir = data_dir.display(),
    );

    if let Some(config_path) = maybe_config_path {
        args.push_str(&format!(
            "        <string>--config</string>\n        <string>{config}</string>\n",
            config = config_path.display(),
        ));
    }

    let mut log_keys = String::new();
    if let Some(log_path) = maybe_log_path {
        log_keys.push_str(&format!(
            "    <key>StandardOutPath</key>\n    <string>{log}</string>\n    <key>StandardErrorPath</key>\n    <string>{log}</string>\n",
            log = log_path.display(),
        ));
    }

    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by Open Bitcoin. Do not edit manually. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
{args}    </array>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>
{log_keys}</dict>
</plist>
"#
    )
}

/// macOS launchd adapter for Open Bitcoin service lifecycle management.
pub struct LaunchdAdapter {
    home_dir: PathBuf,
}

impl LaunchdAdapter {
    /// Create a new `LaunchdAdapter` rooted at the given home directory.
    pub fn new(home_dir: PathBuf) -> Self {
        Self { home_dir }
    }

    fn plist_target_path(&self) -> PathBuf {
        self.home_dir
            .join("Library")
            .join("LaunchAgents")
            .join(OPEN_BITCOIN_LAUNCHD_FILE_NAME)
    }
}

impl ServiceManager for LaunchdAdapter {
    fn install(
        &self,
        request: &ServiceInstallRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let target_path = self.plist_target_path();
        let plist_content = generate_plist_content(
            OPEN_BITCOIN_LAUNCHD_LABEL,
            &request.binary_path,
            &request.data_dir,
            request.maybe_config_path.as_deref(),
            request.maybe_log_path.as_deref(),
        );
        let bootstrap_command =
            format!("launchctl bootstrap gui/$(id -u) {}", target_path.display());

        if !request.apply {
            return Ok(ServiceCommandOutcome {
                dry_run: true,
                description: format!("Would write plist to {}", target_path.display()),
                maybe_file_path: Some(target_path),
                maybe_file_content: Some(plist_content),
                commands_that_would_run: vec![bootstrap_command],
            });
        }

        if target_path.exists() {
            return Err(ServiceError::AlreadyInstalled { path: target_path });
        }

        if let Some(parent) = target_path.parent() {
            std::fs::create_dir_all(parent).map_err(|error| ServiceError::WriteFailure {
                path: parent.to_owned(),
                cause: error.to_string(),
            })?;
        }

        std::fs::write(&target_path, &plist_content).map_err(|error| {
            ServiceError::WriteFailure {
                path: target_path.clone(),
                cause: error.to_string(),
            }
        })?;

        Ok(ServiceCommandOutcome {
            dry_run: false,
            description: format!("Wrote plist to {}", target_path.display()),
            maybe_file_path: Some(target_path),
            maybe_file_content: Some(plist_content),
            commands_that_would_run: vec![bootstrap_command],
        })
    }

    fn uninstall(
        &self,
        request: &ServiceUninstallRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let target_path = self.plist_target_path();
        if !target_path.exists() {
            return Err(ServiceError::NotInstalled);
        }

        let bootout_command = format!(
            "launchctl bootout gui/$(id -u)/{}",
            OPEN_BITCOIN_LAUNCHD_LABEL
        );

        if !request.apply {
            return Ok(ServiceCommandOutcome {
                dry_run: true,
                description: format!("Would remove plist at {}", target_path.display()),
                maybe_file_path: Some(target_path),
                maybe_file_content: None,
                commands_that_would_run: vec![bootout_command],
            });
        }

        std::fs::remove_file(&target_path).map_err(|error| ServiceError::WriteFailure {
            path: target_path.clone(),
            cause: error.to_string(),
        })?;

        Ok(ServiceCommandOutcome {
            dry_run: false,
            description: format!("Removed plist at {}", target_path.display()),
            maybe_file_path: Some(target_path),
            maybe_file_content: None,
            commands_that_would_run: vec![bootout_command],
        })
    }

    fn enable(
        &self,
        _request: &ServiceEnableRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let command = format!(
            "launchctl enable gui/$(id -u)/{}",
            OPEN_BITCOIN_LAUNCHD_LABEL
        );

        let output = std::process::Command::new("launchctl")
            .arg("enable")
            .arg(format!("gui/$(id -u)/{}", OPEN_BITCOIN_LAUNCHD_LABEL))
            .output();

        match output {
            Ok(out) if out.status.success() => Ok(ServiceCommandOutcome {
                dry_run: false,
                description: "Enabled service".to_string(),
                maybe_file_path: None,
                maybe_file_content: None,
                commands_that_would_run: vec![command],
            }),
            Ok(out) => {
                let exit_code = out.status.code().unwrap_or(-1);
                let stderr = String::from_utf8_lossy(&out.stderr).to_string();
                Err(ServiceError::ManagerCommandFailed { exit_code, stderr })
            }
            Err(_) => Ok(ServiceCommandOutcome {
                dry_run: true,
                description: format!(
                    "Would enable service (launchctl not available). Run: {command}"
                ),
                maybe_file_path: None,
                maybe_file_content: None,
                commands_that_would_run: vec![command],
            }),
        }
    }

    fn disable(
        &self,
        _request: &ServiceDisableRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let command = format!(
            "launchctl disable gui/$(id -u)/{}",
            OPEN_BITCOIN_LAUNCHD_LABEL
        );

        let output = std::process::Command::new("launchctl")
            .arg("disable")
            .arg(format!("gui/$(id -u)/{}", OPEN_BITCOIN_LAUNCHD_LABEL))
            .output();

        match output {
            Ok(out) if out.status.success() => Ok(ServiceCommandOutcome {
                dry_run: false,
                description: "Disabled service".to_string(),
                maybe_file_path: None,
                maybe_file_content: None,
                commands_that_would_run: vec![command],
            }),
            Ok(out) => {
                let exit_code = out.status.code().unwrap_or(-1);
                let stderr = String::from_utf8_lossy(&out.stderr).to_string();
                Err(ServiceError::ManagerCommandFailed { exit_code, stderr })
            }
            Err(_) => Ok(ServiceCommandOutcome {
                dry_run: true,
                description: format!(
                    "Would disable service (launchctl not available). Run: {command}"
                ),
                maybe_file_path: None,
                maybe_file_content: None,
                commands_that_would_run: vec![command],
            }),
        }
    }

    fn status(&self) -> Result<ServiceStateSnapshot, ServiceError> {
        let plist_path = self.plist_target_path();
        let installed = plist_path.exists();

        let output = std::process::Command::new("launchctl")
            .arg("list")
            .arg(OPEN_BITCOIN_LAUNCHD_LABEL)
            .output();

        let Ok(out) = output else {
            return Ok(ServiceStateSnapshot {
                state: if installed {
                    ServiceLifecycleState::Installed
                } else {
                    ServiceLifecycleState::Unmanaged
                },
                maybe_service_file_path: installed.then_some(plist_path),
                maybe_manager_diagnostics: Some("launchctl not available".to_string()),
                maybe_log_path: None,
            });
        };

        // Exit code 113 = service not registered with launchd.
        if out.status.code() == Some(113) {
            return Ok(ServiceStateSnapshot {
                state: if installed {
                    ServiceLifecycleState::Installed
                } else {
                    ServiceLifecycleState::Unmanaged
                },
                maybe_service_file_path: installed.then_some(plist_path),
                maybe_manager_diagnostics: None,
                maybe_log_path: None,
            });
        }

        let stdout = String::from_utf8_lossy(&out.stdout).to_string();
        // CF plist text: "PID" = 1234; (launchctl list <label> format)
        let state = if stdout.contains("\"PID\" = ") {
            ServiceLifecycleState::Running
        } else if stdout.contains("\"LastExitStatus\" = 0;") {
            ServiceLifecycleState::Stopped
        } else if out.status.success() {
            ServiceLifecycleState::Failed
        } else if installed {
            ServiceLifecycleState::Installed
        } else {
            ServiceLifecycleState::Unmanaged
        };

        Ok(ServiceStateSnapshot {
            state,
            maybe_service_file_path: installed.then_some(plist_path),
            maybe_manager_diagnostics: if stdout.is_empty() {
                None
            } else {
                Some(stdout)
            },
            maybe_log_path: None,
        })
    }
}
