// Parity breadcrumbs:
// - none: Open Bitcoin-only support/infrastructure; no direct Bitcoin Knots source anchor identified.

//! Linux systemd service adapter for the Open Bitcoin node.
//!
//! `generate_unit_content()` is a pure function exercised in tests without filesystem or
//! subprocess access. `SystemdAdapter` wraps effectful operations (file writes and
//! `systemctl` invocations) behind the `ServiceManager` trait.

use std::path::{Path, PathBuf};

use super::{
    ServiceCommandOutcome, ServiceDisableRequest, ServiceEnableRequest, ServiceError,
    ServiceInstallRequest, ServiceLifecycleState, ServiceManager, ServiceStateSnapshot,
    ServiceUninstallRequest,
};

/// Systemd unit filename for the Open Bitcoin node service.
pub const OPEN_BITCOIN_SYSTEMD_FILE_NAME: &str = "open-bitcoin-node.service";

/// Generate a Linux systemd unit file string for the Open Bitcoin node.
///
/// This is a pure function — no filesystem access or subprocess calls occur here.
pub fn generate_unit_content(
    binary_path: &Path,
    data_dir: &Path,
    maybe_config_path: Option<&Path>,
) -> String {
    let binary_str = binary_path.display();
    let data_dir_str = data_dir.display();

    let config_arg = maybe_config_path
        .map(|p| format!(" --config {}", p.display()))
        .unwrap_or_default();

    format!(
        "# Generated by Open Bitcoin. Do not edit manually.\n\
         [Unit]\n\
         Description=Open Bitcoin Node\n\
         After=network.target\n\
         \n\
         [Service]\n\
         ExecStart={binary_str} --datadir {data_dir_str}{config_arg}\n\
         Restart=on-failure\n\
         StandardOutput=journal\n\
         StandardError=journal\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n"
    )
}

/// Linux systemd user-scope service adapter.
///
/// Wraps unit file writes and `systemctl --user` invocations. Construct via
/// `SystemdAdapter::new()`; inject into CLI routes via the `ServiceManager` trait.
pub struct SystemdAdapter {
    home_dir: PathBuf,
}

impl SystemdAdapter {
    pub fn new(home_dir: PathBuf) -> Self {
        Self { home_dir }
    }

    fn user_systemd_dir(&self) -> PathBuf {
        self.home_dir.join(".config").join("systemd").join("user")
    }

    fn unit_path(&self) -> PathBuf {
        self.user_systemd_dir().join(OPEN_BITCOIN_SYSTEMD_FILE_NAME)
    }
}

impl ServiceManager for SystemdAdapter {
    fn install(
        &self,
        request: &ServiceInstallRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let unit_path = self.unit_path();
        let unit_content = generate_unit_content(
            &request.binary_path,
            &request.data_dir,
            request.maybe_config_path.as_deref(),
        );

        let dry_run_commands = vec![
            "systemctl --user daemon-reload".to_string(),
            "systemctl --user enable open-bitcoin-node.service".to_string(),
        ];

        if !request.apply {
            return Ok(ServiceCommandOutcome {
                dry_run: true,
                description: format!("Would write unit file to {}", unit_path.display()),
                maybe_file_path: Some(unit_path),
                maybe_file_content: Some(unit_content),
                commands_that_would_run: dry_run_commands,
            });
        }

        if unit_path.exists() {
            return Err(ServiceError::AlreadyInstalled { path: unit_path });
        }

        if let Err(cause) = std::fs::create_dir_all(self.user_systemd_dir()) {
            return Err(ServiceError::WriteFailure {
                path: self.user_systemd_dir(),
                cause: cause.to_string(),
            });
        }

        std::fs::write(&unit_path, &unit_content).map_err(|cause| ServiceError::WriteFailure {
            path: unit_path.clone(),
            cause: cause.to_string(),
        })?;

        Ok(ServiceCommandOutcome {
            dry_run: false,
            description: format!("Wrote unit file to {}", unit_path.display()),
            maybe_file_path: Some(unit_path),
            maybe_file_content: Some(unit_content),
            commands_that_would_run: dry_run_commands,
        })
    }

    fn uninstall(
        &self,
        request: &ServiceUninstallRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let unit_path = self.unit_path();
        let disable_cmd = "systemctl --user disable open-bitcoin-node.service".to_string();

        if !unit_path.exists() {
            return Err(ServiceError::NotInstalled);
        }

        if !request.apply {
            return Ok(ServiceCommandOutcome {
                dry_run: true,
                description: format!("Would remove unit file at {}", unit_path.display()),
                maybe_file_path: Some(unit_path),
                maybe_file_content: None,
                commands_that_would_run: vec![disable_cmd],
            });
        }

        // Disable before removing
        let _ = std::process::Command::new("systemctl")
            .args(["--user", "disable", OPEN_BITCOIN_SYSTEMD_FILE_NAME])
            .output();

        std::fs::remove_file(&unit_path).map_err(|cause| ServiceError::WriteFailure {
            path: unit_path.clone(),
            cause: cause.to_string(),
        })?;

        Ok(ServiceCommandOutcome {
            dry_run: false,
            description: format!("Removed unit file at {}", unit_path.display()),
            maybe_file_path: Some(unit_path),
            maybe_file_content: None,
            commands_that_would_run: vec![disable_cmd],
        })
    }

    fn enable(
        &self,
        request: &ServiceEnableRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let enable_cmd = "systemctl --user enable open-bitcoin-node.service".to_string();
        let _ = request;

        let outcome = ServiceCommandOutcome {
            dry_run: false,
            description: "Enabled service to start at login".to_string(),
            maybe_file_path: None,
            maybe_file_content: None,
            commands_that_would_run: vec![enable_cmd],
        };

        let output = std::process::Command::new("systemctl")
            .args(["--user", "enable", OPEN_BITCOIN_SYSTEMD_FILE_NAME])
            .output()
            .map_err(|cause| ServiceError::ManagerCommandFailed {
                exit_code: -1,
                stderr: cause.to_string(),
            })?;

        if !output.status.success() {
            let exit_code = output.status.code().unwrap_or(-1);
            let stderr = String::from_utf8_lossy(&output.stderr).to_string();
            return Err(ServiceError::ManagerCommandFailed { exit_code, stderr });
        }

        Ok(outcome)
    }

    fn disable(
        &self,
        request: &ServiceDisableRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let disable_cmd = "systemctl --user disable open-bitcoin-node.service".to_string();
        let _ = request;

        let outcome = ServiceCommandOutcome {
            dry_run: false,
            description: "Disabled service from starting at login".to_string(),
            maybe_file_path: None,
            maybe_file_content: None,
            commands_that_would_run: vec![disable_cmd],
        };

        let output = std::process::Command::new("systemctl")
            .args(["--user", "disable", OPEN_BITCOIN_SYSTEMD_FILE_NAME])
            .output()
            .map_err(|cause| ServiceError::ManagerCommandFailed {
                exit_code: -1,
                stderr: cause.to_string(),
            })?;

        if !output.status.success() {
            let exit_code = output.status.code().unwrap_or(-1);
            let stderr = String::from_utf8_lossy(&output.stderr).to_string();
            return Err(ServiceError::ManagerCommandFailed { exit_code, stderr });
        }

        Ok(outcome)
    }

    fn status(&self) -> Result<ServiceStateSnapshot, ServiceError> {
        let unit_path = self.unit_path();

        if !unit_path.exists() {
            return Ok(ServiceStateSnapshot {
                state: ServiceLifecycleState::Unmanaged,
                maybe_service_file_path: None,
                maybe_manager_diagnostics: Some(
                    "unmanaged — run `open-bitcoin service install --dry-run` to see what would be created".to_string()
                ),
                maybe_log_path: None,
            });
        }

        let output = std::process::Command::new("systemctl")
            .args(["--user", "is-active", OPEN_BITCOIN_SYSTEMD_FILE_NAME])
            .output();

        let Ok(output) = output else {
            return Ok(ServiceStateSnapshot {
                state: ServiceLifecycleState::Installed,
                maybe_service_file_path: Some(unit_path),
                maybe_manager_diagnostics: Some("systemctl not available".to_string()),
                maybe_log_path: None,
            });
        };

        let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
        let state = match output.status.code() {
            Some(0) => ServiceLifecycleState::Running,
            Some(3) => ServiceLifecycleState::Stopped,
            _ => ServiceLifecycleState::Failed,
        };

        Ok(ServiceStateSnapshot {
            state,
            maybe_service_file_path: Some(unit_path),
            maybe_manager_diagnostics: if stdout.is_empty() {
                None
            } else {
                Some(stdout)
            },
            maybe_log_path: None,
        })
    }
}
