// Parity breadcrumbs:
// - none: Open Bitcoin-only support/infrastructure; no direct Bitcoin Knots source anchor identified.

//! Linux systemd service adapter and unit file content generator for Open Bitcoin.

use std::path::{Path, PathBuf};

use super::{
    ServiceCommandOutcome, ServiceDisableRequest, ServiceEnableRequest, ServiceError,
    ServiceInstallRequest, ServiceLifecycleState, ServiceManager, ServiceStateSnapshot,
    ServiceUninstallRequest,
};

/// systemd user-scope unit file name for the Open Bitcoin node.
pub const OPEN_BITCOIN_SYSTEMD_FILE_NAME: &str = "open-bitcoin-node.service";

/// Generate systemd unit file content for the Open Bitcoin node.
///
/// Returns a complete systemd unit file string. Does not perform any I/O.
pub fn generate_unit_content(
    binary_path: &Path,
    data_dir: &Path,
    maybe_config_path: Option<&Path>,
) -> String {
    let exec_start = if let Some(config_path) = maybe_config_path {
        format!(
            "{binary} --datadir {datadir} --config {config}",
            binary = binary_path.display(),
            datadir = data_dir.display(),
            config = config_path.display(),
        )
    } else {
        format!(
            "{binary} --datadir {datadir}",
            binary = binary_path.display(),
            datadir = data_dir.display(),
        )
    };

    format!(
        "# Generated by Open Bitcoin. Do not edit manually.\n\
         [Unit]\n\
         Description=Open Bitcoin Node\n\
         After=network.target\n\
         \n\
         [Service]\n\
         ExecStart={exec_start}\n\
         Restart=on-failure\n\
         StandardOutput=journal\n\
         StandardError=journal\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n"
    )
}

/// Linux systemd adapter for Open Bitcoin service lifecycle management.
pub struct SystemdAdapter {
    home_dir: PathBuf,
}

impl SystemdAdapter {
    /// Create a new `SystemdAdapter` rooted at the given home directory.
    pub fn new(home_dir: PathBuf) -> Self {
        Self { home_dir }
    }

    fn unit_target_path(&self) -> PathBuf {
        self.home_dir
            .join(".config")
            .join("systemd")
            .join("user")
            .join(OPEN_BITCOIN_SYSTEMD_FILE_NAME)
    }
}

impl ServiceManager for SystemdAdapter {
    fn install(
        &self,
        request: &ServiceInstallRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let target_path = self.unit_target_path();
        let unit_content = generate_unit_content(
            &request.binary_path,
            &request.data_dir,
            request.maybe_config_path.as_deref(),
        );
        let commands_that_would_run = vec![
            "systemctl --user daemon-reload".to_string(),
            "systemctl --user enable open-bitcoin-node.service".to_string(),
        ];

        if !request.apply {
            return Ok(ServiceCommandOutcome {
                dry_run: true,
                description: format!("Would write unit file to {}", target_path.display()),
                maybe_file_path: Some(target_path),
                maybe_file_content: Some(unit_content),
                commands_that_would_run,
            });
        }

        if target_path.exists() {
            return Err(ServiceError::AlreadyInstalled { path: target_path });
        }

        if let Some(parent) = target_path.parent() {
            std::fs::create_dir_all(parent).map_err(|error| ServiceError::WriteFailure {
                path: parent.to_owned(),
                cause: error.to_string(),
            })?;
        }

        std::fs::write(&target_path, &unit_content).map_err(|error| {
            ServiceError::WriteFailure {
                path: target_path.clone(),
                cause: error.to_string(),
            }
        })?;

        Ok(ServiceCommandOutcome {
            dry_run: false,
            description: format!("Wrote unit file to {}", target_path.display()),
            maybe_file_path: Some(target_path),
            maybe_file_content: Some(unit_content),
            commands_that_would_run,
        })
    }

    fn uninstall(
        &self,
        request: &ServiceUninstallRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let target_path = self.unit_target_path();
        if !target_path.exists() {
            return Err(ServiceError::NotInstalled);
        }

        let commands_that_would_run =
            vec!["systemctl --user disable open-bitcoin-node.service".to_string()];

        if !request.apply {
            return Ok(ServiceCommandOutcome {
                dry_run: true,
                description: format!("Would remove unit file at {}", target_path.display()),
                maybe_file_path: Some(target_path),
                maybe_file_content: None,
                commands_that_would_run,
            });
        }

        std::fs::remove_file(&target_path).map_err(|error| ServiceError::WriteFailure {
            path: target_path.clone(),
            cause: error.to_string(),
        })?;

        Ok(ServiceCommandOutcome {
            dry_run: false,
            description: format!("Removed unit file at {}", target_path.display()),
            maybe_file_path: Some(target_path),
            maybe_file_content: None,
            commands_that_would_run,
        })
    }

    fn enable(
        &self,
        _request: &ServiceEnableRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let command = "systemctl --user enable open-bitcoin-node.service".to_string();

        let output = std::process::Command::new("systemctl")
            .arg("--user")
            .arg("enable")
            .arg(OPEN_BITCOIN_SYSTEMD_FILE_NAME)
            .output();

        match output {
            Ok(out) if out.status.success() => Ok(ServiceCommandOutcome {
                dry_run: false,
                description: "Enabled service".to_string(),
                maybe_file_path: None,
                maybe_file_content: None,
                commands_that_would_run: vec![command],
            }),
            Ok(out) => {
                let exit_code = out.status.code().unwrap_or(-1);
                let stderr = String::from_utf8_lossy(&out.stderr).to_string();
                Err(ServiceError::ManagerCommandFailed { exit_code, stderr })
            }
            Err(_) => Ok(ServiceCommandOutcome {
                dry_run: true,
                description: format!(
                    "Would enable service (systemctl not available). Run: {command}"
                ),
                maybe_file_path: None,
                maybe_file_content: None,
                commands_that_would_run: vec![command],
            }),
        }
    }

    fn disable(
        &self,
        _request: &ServiceDisableRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let command = "systemctl --user disable open-bitcoin-node.service".to_string();

        let output = std::process::Command::new("systemctl")
            .arg("--user")
            .arg("disable")
            .arg(OPEN_BITCOIN_SYSTEMD_FILE_NAME)
            .output();

        match output {
            Ok(out) if out.status.success() => Ok(ServiceCommandOutcome {
                dry_run: false,
                description: "Disabled service".to_string(),
                maybe_file_path: None,
                maybe_file_content: None,
                commands_that_would_run: vec![command],
            }),
            Ok(out) => {
                let exit_code = out.status.code().unwrap_or(-1);
                let stderr = String::from_utf8_lossy(&out.stderr).to_string();
                Err(ServiceError::ManagerCommandFailed { exit_code, stderr })
            }
            Err(_) => Ok(ServiceCommandOutcome {
                dry_run: true,
                description: format!(
                    "Would disable service (systemctl not available). Run: {command}"
                ),
                maybe_file_path: None,
                maybe_file_content: None,
                commands_that_would_run: vec![command],
            }),
        }
    }

    fn status(&self) -> Result<ServiceStateSnapshot, ServiceError> {
        let unit_path = self.unit_target_path();
        let installed = unit_path.exists();

        let output = std::process::Command::new("systemctl")
            .arg("--user")
            .arg("is-active")
            .arg(OPEN_BITCOIN_SYSTEMD_FILE_NAME)
            .output();

        let Ok(out) = output else {
            return Ok(ServiceStateSnapshot {
                state: if installed {
                    ServiceLifecycleState::Installed
                } else {
                    ServiceLifecycleState::Unmanaged
                },
                maybe_service_file_path: installed.then_some(unit_path),
                maybe_manager_diagnostics: Some("systemctl not available".to_string()),
                maybe_log_path: None,
            });
        };

        // Exit code 0 = active (running), exit 3 = inactive, other = failed/unknown.
        let state = match out.status.code() {
            Some(0) => ServiceLifecycleState::Running,
            Some(3) => ServiceLifecycleState::Stopped,
            _ if installed => ServiceLifecycleState::Failed,
            _ => ServiceLifecycleState::Unmanaged,
        };

        let stdout = String::from_utf8_lossy(&out.stdout).to_string();
        Ok(ServiceStateSnapshot {
            state,
            maybe_service_file_path: installed.then_some(unit_path),
            maybe_manager_diagnostics: if stdout.trim().is_empty() {
                None
            } else {
                Some(stdout)
            },
            maybe_log_path: None,
        })
    }
}
