// Parity breadcrumbs:
// - none: Open Bitcoin-only support/infrastructure; no direct Bitcoin Knots source anchor identified.

//! Linux systemd service adapter for the Open Bitcoin node.
//!
//! `generate_unit_content()` is a pure function exercised in tests without filesystem or
//! subprocess access. `SystemdAdapter` wraps effectful operations (file writes and
//! `systemctl` invocations) behind the `ServiceManager` trait.

use std::path::{Path, PathBuf};

use super::{
    ServiceCommandOutcome, ServiceDisableRequest, ServiceEnableRequest, ServiceError,
    ServiceInstallRequest, ServiceLifecycleState, ServiceManager, ServiceStateSnapshot,
    ServiceUninstallRequest,
};

/// Systemd unit filename for the Open Bitcoin node service.
pub const OPEN_BITCOIN_SYSTEMD_FILE_NAME: &str = "open-bitcoin-node.service";

/// Generate a Linux systemd unit file string for the Open Bitcoin node.
///
/// This is a pure function — no filesystem access or subprocess calls occur here.
pub fn generate_unit_content(
    binary_path: &Path,
    data_dir: &Path,
    maybe_config_path: Option<&Path>,
    maybe_log_path: Option<&Path>,
) -> String {
    let binary_str = binary_path.display();
    let data_dir_str = data_dir.display();

    let config_arg = maybe_config_path
        .map(|p| format!(" --config \"{}\"", p.display()))
        .unwrap_or_default();
    let log_directives = maybe_log_path
        .map(|log_path| {
            format!(
                "StandardOutput=append:{}\n\
         StandardError=append:{}",
                log_path.display(),
                log_path.display()
            )
        })
        .unwrap_or_else(|| {
            "StandardOutput=journal\n\
         StandardError=journal"
                .to_string()
        });

    format!(
        "# Generated by Open Bitcoin. Do not edit manually.\n\
         [Unit]\n\
         Description=Open Bitcoin Node\n\
         After=network.target\n\
         \n\
         [Service]\n\
         ExecStart=\"{binary_str}\" --datadir \"{data_dir_str}\"{config_arg}\n\
         Restart=on-failure\n\
         {log_directives}\n\
         \n\
         [Install]\n\
         WantedBy=default.target\n"
    )
}

fn systemd_install_commands() -> Vec<String> {
    vec![
        "systemctl --user daemon-reload".to_string(),
        format!("systemctl --user enable {OPEN_BITCOIN_SYSTEMD_FILE_NAME}"),
    ]
}

fn systemd_uninstall_commands() -> Vec<String> {
    vec![
        format!("systemctl --user disable {OPEN_BITCOIN_SYSTEMD_FILE_NAME}"),
        "systemctl --user daemon-reload".to_string(),
    ]
}

pub(crate) fn parse_systemd_enabled_state(output: &str) -> Option<bool> {
    let normalized = output.trim().to_ascii_lowercase();
    match normalized.as_str() {
        "enabled" | "enabled-runtime" => Some(true),
        "alias" | "disabled" | "generated" | "indirect" | "linked" | "linked-runtime"
        | "masked" | "static" | "transient" => Some(false),
        _ => None,
    }
}

pub(crate) fn parse_systemd_log_path(unit_content: &str) -> Option<PathBuf> {
    for line in unit_content.lines() {
        let trimmed = line.trim();
        let maybe_value = trimmed
            .strip_prefix("StandardOutput=")
            .or_else(|| trimmed.strip_prefix("StandardError="));
        let Some(value) = maybe_value else {
            continue;
        };

        if let Some(path) = value
            .strip_prefix("append:")
            .or_else(|| value.strip_prefix("file:"))
        {
            return Some(PathBuf::from(path.trim_matches('"')));
        }
    }

    None
}

/// Linux systemd user-scope service adapter.
///
/// Wraps unit file writes and `systemctl --user` invocations. Construct via
/// `SystemdAdapter::new()`; inject into CLI routes via the `ServiceManager` trait.
pub struct SystemdAdapter {
    home_dir: PathBuf,
}

impl SystemdAdapter {
    pub fn new(home_dir: PathBuf) -> Self {
        Self { home_dir }
    }

    fn user_systemd_dir(&self) -> PathBuf {
        self.home_dir.join(".config").join("systemd").join("user")
    }

    fn unit_path(&self) -> PathBuf {
        self.user_systemd_dir().join(OPEN_BITCOIN_SYSTEMD_FILE_NAME)
    }

    fn log_path_status(&self, unit_path: &Path) -> (Option<PathBuf>, Option<String>) {
        let unit_content = match std::fs::read_to_string(unit_path) {
            Ok(content) => content,
            Err(error) => {
                return (
                    None,
                    Some(format!(
                        "could not read installed unit for log path: {error}"
                    )),
                );
            }
        };

        if let Some(log_path) = parse_systemd_log_path(&unit_content) {
            return (Some(log_path), None);
        }
        if unit_content.lines().any(|line| {
            matches!(
                line.trim(),
                "StandardOutput=journal" | "StandardError=journal"
            )
        }) {
            return (
                None,
                Some("installed unit routes service output to journald".to_string()),
            );
        }

        (
            None,
            Some("installed unit does not declare a file-backed service log path".to_string()),
        )
    }
}

impl ServiceManager for SystemdAdapter {
    fn install(
        &self,
        request: &ServiceInstallRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let unit_path = self.unit_path();
        let unit_content = generate_unit_content(
            &request.binary_path,
            &request.data_dir,
            request.maybe_config_path.as_deref(),
            request.maybe_log_path.as_deref(),
        );

        let install_commands = systemd_install_commands();

        if !request.apply {
            return Ok(ServiceCommandOutcome {
                dry_run: true,
                description: format!("Would write unit file to {}", unit_path.display()),
                maybe_file_path: Some(unit_path),
                maybe_file_content: Some(unit_content),
                commands_that_would_run: install_commands,
            });
        }

        if unit_path.exists() {
            return Err(ServiceError::AlreadyInstalled { path: unit_path });
        }

        if let Err(cause) = std::fs::create_dir_all(self.user_systemd_dir()) {
            return Err(ServiceError::WriteFailure {
                path: self.user_systemd_dir(),
                cause: cause.to_string(),
            });
        }

        std::fs::write(&unit_path, &unit_content).map_err(|cause| ServiceError::WriteFailure {
            path: unit_path.clone(),
            cause: cause.to_string(),
        })?;

        let reload_output = std::process::Command::new("systemctl")
            .args(["--user", "daemon-reload"])
            .output()
            .map_err(|cause| ServiceError::ManagerCommandFailed {
                exit_code: -1,
                stderr: cause.to_string(),
            })?;
        if !reload_output.status.success() {
            let exit_code = reload_output.status.code().unwrap_or(-1);
            let stderr = String::from_utf8_lossy(&reload_output.stderr).to_string();
            return Err(ServiceError::ManagerCommandFailed { exit_code, stderr });
        }

        let enable_output = std::process::Command::new("systemctl")
            .args(["--user", "enable", OPEN_BITCOIN_SYSTEMD_FILE_NAME])
            .output()
            .map_err(|cause| ServiceError::ManagerCommandFailed {
                exit_code: -1,
                stderr: cause.to_string(),
            })?;
        if !enable_output.status.success() {
            let exit_code = enable_output.status.code().unwrap_or(-1);
            let stderr = String::from_utf8_lossy(&enable_output.stderr).to_string();
            return Err(ServiceError::ManagerCommandFailed { exit_code, stderr });
        }

        Ok(ServiceCommandOutcome {
            dry_run: false,
            description: format!(
                "Wrote unit file to {} and reloaded or enabled it in systemd",
                unit_path.display()
            ),
            maybe_file_path: Some(unit_path),
            maybe_file_content: Some(unit_content),
            commands_that_would_run: install_commands,
        })
    }

    fn uninstall(
        &self,
        request: &ServiceUninstallRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let unit_path = self.unit_path();
        let uninstall_commands = systemd_uninstall_commands();

        if !unit_path.exists() {
            return Err(ServiceError::NotInstalled);
        }

        if !request.apply {
            return Ok(ServiceCommandOutcome {
                dry_run: true,
                description: format!("Would remove unit file at {}", unit_path.display()),
                maybe_file_path: Some(unit_path),
                maybe_file_content: None,
                commands_that_would_run: uninstall_commands,
            });
        }

        // Disable before removing; propagate failure so the enable symlink is not orphaned.
        let disable_output = std::process::Command::new("systemctl")
            .args(["--user", "disable", OPEN_BITCOIN_SYSTEMD_FILE_NAME])
            .output()
            .map_err(|cause| ServiceError::ManagerCommandFailed {
                exit_code: -1,
                stderr: cause.to_string(),
            })?;
        if !disable_output.status.success() {
            let exit_code = disable_output.status.code().unwrap_or(-1);
            let stderr = String::from_utf8_lossy(&disable_output.stderr).to_string();
            return Err(ServiceError::ManagerCommandFailed { exit_code, stderr });
        }

        std::fs::remove_file(&unit_path).map_err(|cause| ServiceError::WriteFailure {
            path: unit_path.clone(),
            cause: cause.to_string(),
        })?;

        let reload_output = std::process::Command::new("systemctl")
            .args(["--user", "daemon-reload"])
            .output()
            .map_err(|cause| ServiceError::ManagerCommandFailed {
                exit_code: -1,
                stderr: cause.to_string(),
            })?;
        if !reload_output.status.success() {
            let exit_code = reload_output.status.code().unwrap_or(-1);
            let stderr = String::from_utf8_lossy(&reload_output.stderr).to_string();
            return Err(ServiceError::ManagerCommandFailed { exit_code, stderr });
        }

        Ok(ServiceCommandOutcome {
            dry_run: false,
            description: format!("Removed unit file at {}", unit_path.display()),
            maybe_file_path: Some(unit_path),
            maybe_file_content: None,
            commands_that_would_run: uninstall_commands,
        })
    }

    fn enable(
        &self,
        request: &ServiceEnableRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let enable_cmd = "systemctl --user enable open-bitcoin-node.service".to_string();
        let _ = request;

        let outcome = ServiceCommandOutcome {
            dry_run: false,
            description: "Enabled service to start at login".to_string(),
            maybe_file_path: None,
            maybe_file_content: None,
            commands_that_would_run: vec![enable_cmd],
        };

        let output = std::process::Command::new("systemctl")
            .args(["--user", "enable", OPEN_BITCOIN_SYSTEMD_FILE_NAME])
            .output()
            .map_err(|cause| ServiceError::ManagerCommandFailed {
                exit_code: -1,
                stderr: cause.to_string(),
            })?;

        if !output.status.success() {
            let exit_code = output.status.code().unwrap_or(-1);
            let stderr = String::from_utf8_lossy(&output.stderr).to_string();
            return Err(ServiceError::ManagerCommandFailed { exit_code, stderr });
        }

        Ok(outcome)
    }

    fn disable(
        &self,
        request: &ServiceDisableRequest,
    ) -> Result<ServiceCommandOutcome, ServiceError> {
        let disable_cmd = "systemctl --user disable open-bitcoin-node.service".to_string();
        let _ = request;

        let outcome = ServiceCommandOutcome {
            dry_run: false,
            description: "Disabled service from starting at login".to_string(),
            maybe_file_path: None,
            maybe_file_content: None,
            commands_that_would_run: vec![disable_cmd],
        };

        let output = std::process::Command::new("systemctl")
            .args(["--user", "disable", OPEN_BITCOIN_SYSTEMD_FILE_NAME])
            .output()
            .map_err(|cause| ServiceError::ManagerCommandFailed {
                exit_code: -1,
                stderr: cause.to_string(),
            })?;

        if !output.status.success() {
            let exit_code = output.status.code().unwrap_or(-1);
            let stderr = String::from_utf8_lossy(&output.stderr).to_string();
            return Err(ServiceError::ManagerCommandFailed { exit_code, stderr });
        }

        Ok(outcome)
    }

    fn status(&self) -> Result<ServiceStateSnapshot, ServiceError> {
        let unit_path = self.unit_path();

        if !unit_path.exists() {
            return Ok(ServiceStateSnapshot {
                state: ServiceLifecycleState::Unmanaged,
                maybe_enabled: Some(false),
                maybe_service_file_path: None,
                maybe_manager_diagnostics: Some(
                    "unmanaged — run `open-bitcoin service install` to preview what would be created".to_string()
                ),
                maybe_log_path: None,
                maybe_log_path_unavailable_reason: Some("service not installed".to_string()),
            });
        }

        let (maybe_log_path, maybe_log_path_unavailable_reason) = self.log_path_status(&unit_path);
        let (maybe_enabled, maybe_enabled_diagnostics) =
            match std::process::Command::new("systemctl")
                .args(["--user", "is-enabled", OPEN_BITCOIN_SYSTEMD_FILE_NAME])
                .output()
            {
                Ok(output) => {
                    let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
                    let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
                    let maybe_enabled = parse_systemd_enabled_state(&stdout);
                    let maybe_diagnostic = if stderr.is_empty() {
                        None
                    } else {
                        Some(format!("systemctl is-enabled reported: {stderr}"))
                    };
                    (maybe_enabled, maybe_diagnostic)
                }
                Err(_) => (None, Some("systemctl is-enabled not available".to_string())),
            };

        let output = std::process::Command::new("systemctl")
            .args(["--user", "is-active", OPEN_BITCOIN_SYSTEMD_FILE_NAME])
            .output();

        let Ok(output) = output else {
            return Ok(ServiceStateSnapshot {
                state: maybe_enabled
                    .map(|enabled| {
                        if enabled {
                            ServiceLifecycleState::Enabled
                        } else {
                            ServiceLifecycleState::Installed
                        }
                    })
                    .unwrap_or(ServiceLifecycleState::Installed),
                maybe_enabled,
                maybe_service_file_path: Some(unit_path),
                maybe_manager_diagnostics: maybe_enabled_diagnostics
                    .or_else(|| Some("systemctl not available".to_string())),
                maybe_log_path,
                maybe_log_path_unavailable_reason,
            });
        };

        let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
        let state = match stdout.as_str() {
            "active" => ServiceLifecycleState::Running,
            "failed" => ServiceLifecycleState::Failed,
            "inactive" => {
                if maybe_enabled == Some(true) {
                    ServiceLifecycleState::Stopped
                } else {
                    ServiceLifecycleState::Installed
                }
            }
            _ if maybe_enabled == Some(true) => ServiceLifecycleState::Enabled,
            _ if maybe_enabled == Some(false) => ServiceLifecycleState::Installed,
            _ => match output.status.code() {
                Some(0) => ServiceLifecycleState::Running,
                Some(3) => ServiceLifecycleState::Stopped,
                _ => ServiceLifecycleState::Failed,
            },
        };

        let mut diagnostics = Vec::new();
        if !stdout.is_empty() {
            diagnostics.push(format!("systemctl is-active={stdout}"));
        }
        if let Some(enabled) = maybe_enabled {
            diagnostics.push(format!("systemctl is-enabled={enabled}"));
        }
        if let Some(diagnostic) = maybe_enabled_diagnostics {
            diagnostics.push(diagnostic);
        }

        Ok(ServiceStateSnapshot {
            state,
            maybe_enabled,
            maybe_service_file_path: Some(unit_path),
            maybe_manager_diagnostics: if diagnostics.is_empty() {
                None
            } else {
                Some(diagnostics.join("\n"))
            },
            maybe_log_path,
            maybe_log_path_unavailable_reason,
        })
    }
}
