// Parity breadcrumbs:
// - none: Open Bitcoin-only support/infrastructure; no direct Bitcoin Knots source anchor identified.

//! Tests for service lifecycle pure generators and fake adapter.

use std::{
    path::{Path, PathBuf},
    sync::atomic::{AtomicU64, Ordering},
};

use crate::operator::service::fake::{FakeServiceCall, FakeServiceManager};
use crate::operator::service::launchd::{LaunchdAdapter, generate_plist_content};
use crate::operator::service::systemd::{SystemdAdapter, generate_unit_content};
use crate::operator::service::{
    ServiceError, ServiceInstallRequest, ServiceLifecycleState, ServiceManager,
    ServiceStateSnapshot,
};

static NEXT_TEST_DIRECTORY_ID: AtomicU64 = AtomicU64::new(0);

struct TestDirectory {
    path: PathBuf,
}

impl TestDirectory {
    fn new(label: &str) -> Self {
        let directory = std::env::temp_dir().join(format!(
            "open-bitcoin-service-tests-{label}-{}",
            NEXT_TEST_DIRECTORY_ID.fetch_add(1, Ordering::Relaxed)
        ));
        std::fs::create_dir_all(&directory).expect("test directory");
        Self { path: directory }
    }
}

impl Drop for TestDirectory {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.path);
    }
}

#[test]
fn plist_content_contains_required_fields() {
    // Arrange
    let binary_path = Path::new("/fake/bin/open-bitcoin");
    let data_dir = Path::new("/fake/datadir");

    // Act
    let plist = generate_plist_content("org.open-bitcoin.node", binary_path, data_dir, None, None);

    // Assert
    assert!(
        plist.contains("<string>org.open-bitcoin.node</string>"),
        "plist must contain label"
    );
    assert!(
        plist.contains("<string>/fake/bin/open-bitcoin</string>"),
        "plist must contain binary path"
    );
    assert!(
        plist.contains("<string>/fake/datadir</string>"),
        "plist must contain data dir"
    );
    assert!(
        plist.contains("<true/>"),
        "plist must contain true (KeepAlive/RunAtLoad)"
    );
    assert!(
        plist.contains("Generated by Open Bitcoin"),
        "plist must contain generator comment"
    );
}

#[test]
fn plist_content_includes_config_path_when_provided() {
    // Arrange
    let binary_path = Path::new("/fake/bin/open-bitcoin");
    let data_dir = Path::new("/fake/datadir");
    let config_path = Path::new("/fake/config.jsonc");

    // Act
    let plist = generate_plist_content(
        "org.open-bitcoin.node",
        binary_path,
        data_dir,
        Some(config_path),
        None,
    );

    // Assert
    assert!(
        plist.contains("<string>/fake/config.jsonc</string>"),
        "plist must contain config path"
    );
    assert!(
        plist.contains("--config"),
        "plist must contain --config flag"
    );
}

#[test]
fn plist_content_includes_log_paths_when_provided() {
    // Arrange
    let binary_path = Path::new("/fake/bin/open-bitcoin");
    let data_dir = Path::new("/fake/datadir");
    let log_path = Path::new("/fake/logs/open-bitcoin.log");

    // Act
    let plist = generate_plist_content(
        "org.open-bitcoin.node",
        binary_path,
        data_dir,
        None,
        Some(log_path),
    );

    // Assert
    assert!(
        plist.contains("StandardOutPath"),
        "plist must contain StandardOutPath key"
    );
    assert!(
        plist.contains("StandardErrorPath"),
        "plist must contain StandardErrorPath key"
    );
    assert!(
        plist.contains("/fake/logs/open-bitcoin.log"),
        "plist must contain log path"
    );
}

#[test]
fn unit_content_contains_required_fields() {
    // Arrange
    let binary_path = Path::new("/fake/bin/open-bitcoin");
    let data_dir = Path::new("/fake/datadir");

    // Act
    let unit = generate_unit_content(binary_path, data_dir, None);

    // Assert
    assert!(unit.contains("[Unit]"), "unit must contain [Unit] section");
    assert!(
        unit.contains("[Service]"),
        "unit must contain [Service] section"
    );
    assert!(
        unit.contains("[Install]"),
        "unit must contain [Install] section"
    );
    assert!(
        unit.contains("ExecStart=/fake/bin/open-bitcoin --datadir /fake/datadir"),
        "unit must contain ExecStart with binary and datadir"
    );
    assert!(
        unit.contains("Restart=on-failure"),
        "unit must contain Restart=on-failure"
    );
    assert!(
        unit.contains("WantedBy=default.target"),
        "unit must contain WantedBy=default.target"
    );
    assert!(
        unit.contains("# Generated by Open Bitcoin"),
        "unit must contain generator comment"
    );
}

#[test]
fn unit_content_includes_config_path_when_provided() {
    // Arrange
    let binary_path = Path::new("/fake/bin/open-bitcoin");
    let data_dir = Path::new("/fake/datadir");
    let config_path = Path::new("/fake/config.jsonc");

    // Act
    let unit = generate_unit_content(binary_path, data_dir, Some(config_path));

    // Assert
    assert!(
        unit.contains("--config /fake/config.jsonc"),
        "unit must contain --config path"
    );
}

#[test]
fn fake_manager_install_records_call() {
    // Arrange
    let snapshot = ServiceStateSnapshot {
        state: ServiceLifecycleState::Unmanaged,
        maybe_service_file_path: None,
        maybe_manager_diagnostics: None,
        maybe_log_path: None,
    };
    let manager = FakeServiceManager::new(snapshot);
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoin"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: true,
    };

    // Act
    let result = manager.install(&request);

    // Assert
    assert!(result.is_ok(), "install must succeed");
    let outcome = result.expect("install outcome");
    assert!(!outcome.dry_run, "apply=true must produce dry_run=false");
    let calls = manager.recorded_calls.borrow();
    assert_eq!(calls.len(), 1);
    assert_eq!(calls[0], FakeServiceCall::Install { apply: true });
}

#[test]
fn fake_manager_status_returns_configured_state() {
    // Arrange
    let snapshot = ServiceStateSnapshot {
        state: ServiceLifecycleState::Unmanaged,
        maybe_service_file_path: None,
        maybe_manager_diagnostics: None,
        maybe_log_path: None,
    };
    let manager = FakeServiceManager::new(snapshot);

    // Act
    let result = manager.status();

    // Assert
    assert!(result.is_ok(), "status must succeed");
    let returned_snapshot = result.expect("status snapshot");
    assert_eq!(returned_snapshot.state, ServiceLifecycleState::Unmanaged);
}

#[test]
fn service_error_unsupported_platform_displays_reason() {
    // Arrange
    let error = ServiceError::UnsupportedPlatform {
        reason: "test platform is not supported".to_string(),
    };

    // Act
    let display = error.to_string();

    // Assert
    assert!(
        display.contains("test platform is not supported"),
        "UnsupportedPlatform display must contain reason: {display}"
    );
}

#[test]
fn service_error_already_installed_displays_path() {
    // Arrange
    let path = PathBuf::from("/some/path/to/service.plist");
    let error = ServiceError::AlreadyInstalled { path: path.clone() };

    // Act
    let display = error.to_string();

    // Assert
    assert!(
        display.contains("/some/path/to/service.plist"),
        "AlreadyInstalled display must contain path: {display}"
    );
}

#[test]
fn launchd_install_dry_run_does_not_write_file() {
    // Arrange
    let test_dir = TestDirectory::new("launchd-dryrun");
    let adapter = LaunchdAdapter::new(test_dir.path.clone());
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoin"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: false,
    };

    // Act
    let result = adapter.install(&request);

    // Assert
    assert!(result.is_ok(), "dry-run install must succeed");
    let outcome = result.expect("install outcome");
    assert!(outcome.dry_run, "apply=false must produce dry_run=true");

    let plist_path = test_dir
        .path
        .join("Library")
        .join("LaunchAgents")
        .join("org.open-bitcoin.node.plist");
    assert!(
        !plist_path.exists(),
        "dry-run install must not write plist file"
    );
}

#[test]
fn systemd_install_dry_run_does_not_write_file() {
    // Arrange
    let test_dir = TestDirectory::new("systemd-dryrun");
    let adapter = SystemdAdapter::new(test_dir.path.clone());
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoin"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: false,
    };

    // Act
    let result = adapter.install(&request);

    // Assert
    assert!(result.is_ok(), "dry-run install must succeed");
    let outcome = result.expect("install outcome");
    assert!(outcome.dry_run, "apply=false must produce dry_run=true");

    let unit_path = test_dir
        .path
        .join(".config")
        .join("systemd")
        .join("user")
        .join("open-bitcoin-node.service");
    assert!(
        !unit_path.exists(),
        "dry-run install must not write unit file"
    );
}

// Silence unused import warning when compiling tests — the trait import is needed for method dispatch.
#[allow(unused_imports)]
use crate::operator::service::ServiceManager as _;

// --- execute_service_command tests ---

use crate::operator::service::execute_service_command;
use crate::operator::{ServiceArgs, ServiceCommand};

fn unmanaged_snapshot() -> ServiceStateSnapshot {
    ServiceStateSnapshot {
        state: ServiceLifecycleState::Unmanaged,
        maybe_service_file_path: None,
        maybe_manager_diagnostics: None,
        maybe_log_path: None,
    }
}

#[test]
fn execute_install_dry_run_returns_success_with_dry_run_indicator() {
    // Arrange
    let manager = FakeServiceManager::new(unmanaged_snapshot());
    let args = ServiceArgs {
        command: ServiceCommand::Install,
        apply: false,
    };

    // Act
    let outcome = execute_service_command(
        &args,
        PathBuf::from("/fake/bin/open-bitcoin"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success
    );
    let stdout = &outcome.stdout.text;
    assert!(
        stdout.to_lowercase().contains("dry run")
            || stdout.to_lowercase().contains("dry-run")
            || stdout.contains("--apply"),
        "dry-run install stdout must mention dry run or --apply: {stdout}"
    );
}

#[test]
fn execute_install_apply_with_already_installed_error_returns_failure() {
    // Arrange
    let mut manager = FakeServiceManager::new(unmanaged_snapshot());
    manager.install_error = Some(ServiceError::AlreadyInstalled {
        path: PathBuf::from("/fake/Library/LaunchAgents/org.open-bitcoin.node.plist"),
    });
    let args = ServiceArgs {
        command: ServiceCommand::Install,
        apply: true,
    };

    // Act
    let outcome = execute_service_command(
        &args,
        PathBuf::from("/fake/bin/open-bitcoin"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Failure(1)
    );
    let stderr = &outcome.stderr.text;
    assert!(
        stderr.to_lowercase().contains("already installed"),
        "apply install with AlreadyInstalled must produce 'already installed' in stderr: {stderr}"
    );
}

#[test]
fn execute_enable_returns_success_with_command_string() {
    // Arrange
    let mut manager = FakeServiceManager::new(unmanaged_snapshot());
    manager.enable_commands =
        vec!["launchctl enable gui/$(id -u)/org.open-bitcoin.node".to_string()];
    let args = ServiceArgs {
        command: ServiceCommand::Enable,
        apply: false,
    };

    // Act
    let outcome = execute_service_command(
        &args,
        PathBuf::from("/fake/bin/open-bitcoin"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success
    );
    let stdout = &outcome.stdout.text;
    assert!(
        stdout.contains("launchctl") || stdout.contains("systemctl"),
        "enable output must contain launchctl or systemctl command: {stdout}"
    );
}

#[test]
fn execute_uninstall_with_not_installed_returns_failure() {
    // Arrange
    let mut manager = FakeServiceManager::new(unmanaged_snapshot());
    manager.uninstall_error = Some(ServiceError::NotInstalled);
    let args = ServiceArgs {
        command: ServiceCommand::Uninstall,
        apply: false,
    };

    // Act
    let outcome = execute_service_command(
        &args,
        PathBuf::from("/fake/bin/open-bitcoin"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Failure(1)
    );
    let stderr = &outcome.stderr.text;
    assert!(
        stderr.to_lowercase().contains("not installed"),
        "uninstall with NotInstalled must produce 'not installed' in stderr: {stderr}"
    );
}

#[test]
fn parse_service_install_with_apply_flag() {
    // Arrange
    use crate::operator::OperatorCli;
    use clap::Parser;

    // Act
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "install", "--apply"])
        .expect("parse must succeed");

    // Assert
    let crate::operator::OperatorCommand::Service(service_args) = cli.command else {
        panic!("expected Service command");
    };
    assert!(service_args.apply, "--apply flag must be true");
    assert_eq!(service_args.command, ServiceCommand::Install);
}

#[test]
fn parse_service_install_without_apply_flag_defaults_false() {
    // Arrange
    use crate::operator::OperatorCli;
    use clap::Parser;

    // Act
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "install"])
        .expect("parse must succeed");

    // Assert
    let crate::operator::OperatorCommand::Service(service_args) = cli.command else {
        panic!("expected Service command");
    };
    assert!(!service_args.apply, "--apply flag must default to false");
}
