// Parity breadcrumbs:
// - none: Open Bitcoin-only support/infrastructure; no direct Bitcoin Knots source anchor identified.

//! Tests for service lifecycle generators, FakeServiceManager, dry-run safety,
//! and execute_service_command dispatch.

use std::{
    path::{Path, PathBuf},
    sync::atomic::{AtomicU64, Ordering},
};

use clap::Parser as _;

use crate::operator::{
    OperatorCli, ServiceCommand,
    service::{
        ServiceCommandOutcome, ServiceError, ServiceInstallRequest, ServiceLifecycleState,
        ServiceManager, ServiceRestartRequest, ServiceStartRequest, ServiceStateSnapshot,
        ServiceStopRequest, execute_service_command,
        fake::{FakeServiceCall, FakeServiceManager},
        launchd::{
            LaunchdAdapter, generate_plist_content, launchd_restart_command, launchd_start_command,
            launchd_stop_command, parse_launchd_disabled_services, parse_launchd_log_path,
        },
        service_log_path_from_log_dir,
        systemd::{
            SystemdAdapter, generate_unit_content, parse_systemd_enabled_state,
            parse_systemd_log_path, systemd_restart_command, systemd_start_command,
            systemd_stop_command,
        },
    },
};

static NEXT_TEST_DIRECTORY_ID: AtomicU64 = AtomicU64::new(0);

/// RAII temp directory for isolation in service tests.
struct TestDirectory {
    path: PathBuf,
}

impl TestDirectory {
    fn new(label: &str) -> Self {
        let directory = std::env::temp_dir().join(format!(
            "open-bitcoin-service-tests-{label}-{}",
            NEXT_TEST_DIRECTORY_ID.fetch_add(1, Ordering::Relaxed)
        ));
        std::fs::create_dir_all(&directory).expect("test directory");
        Self { path: directory }
    }
}

impl Drop for TestDirectory {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.path);
    }
}

// --- Plist generator tests ---

#[test]
fn plist_content_contains_required_fields() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoind");
    let datadir = Path::new("/fake/datadir");

    // Act
    let content = generate_plist_content("org.open-bitcoin.node", binary, datadir, None, None);

    // Assert
    assert!(
        content.contains("<string>org.open-bitcoin.node</string>"),
        "missing label: {content}"
    );
    assert!(
        content.contains("<string>/fake/bin/open-bitcoind</string>"),
        "missing binary path: {content}"
    );
    assert!(
        !content.contains("<string>/fake/bin/open-bitcoin</string>"),
        "plist should not supervise operator binary: {content}"
    );
    assert!(
        content.contains("<string>/fake/datadir</string>"),
        "missing datadir: {content}"
    );
    assert!(
        content.contains("<true/>"),
        "missing KeepAlive or RunAtLoad: {content}"
    );
    assert!(
        content.contains("Generated by Open Bitcoin"),
        "missing comment header: {content}"
    );
}

#[test]
fn plist_content_includes_config_path_when_provided() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoind");
    let datadir = Path::new("/fake/datadir");
    let config = Path::new("/fake/config/open-bitcoin.jsonc");

    // Act
    let content =
        generate_plist_content("org.open-bitcoin.node", binary, datadir, Some(config), None);

    // Assert
    assert!(
        content.contains("<string>--config</string>"),
        "missing --config arg: {content}"
    );
    assert!(
        content.contains("<string>/fake/config/open-bitcoin.jsonc</string>"),
        "missing config path: {content}"
    );
}

#[test]
fn plist_content_includes_log_paths_when_provided() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoind");
    let datadir = Path::new("/fake/datadir");
    let log = Path::new("/fake/logs/open-bitcoin.log");

    // Act
    let content = generate_plist_content("org.open-bitcoin.node", binary, datadir, None, Some(log));

    // Assert
    assert!(
        content.contains("StandardOutPath"),
        "missing StandardOutPath: {content}"
    );
    assert!(
        content.contains("StandardErrorPath"),
        "missing StandardErrorPath: {content}"
    );
    assert!(
        content.contains("/fake/logs/open-bitcoin.log"),
        "missing log path: {content}"
    );
}

#[test]
fn service_log_path_from_log_dir_appends_default_file_name() {
    // Arrange
    let log_dir = Path::new("/fake/logs");

    // Act
    let maybe_log_path = service_log_path_from_log_dir(Some(log_dir));

    // Assert
    assert_eq!(
        maybe_log_path,
        Some(PathBuf::from("/fake/logs/open-bitcoin.log"))
    );
}

// --- Unit file generator tests ---

#[test]
fn unit_content_contains_required_fields() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoind");
    let datadir = Path::new("/fake/datadir");

    // Act
    let content = generate_unit_content(binary, datadir, None, None);

    // Assert
    assert!(content.contains("[Unit]"), "missing [Unit]: {content}");
    assert!(
        content.contains("[Service]"),
        "missing [Service]: {content}"
    );
    assert!(
        content.contains("[Install]"),
        "missing [Install]: {content}"
    );
    assert!(
        content.contains("ExecStart=\"/fake/bin/open-bitcoind\" --datadir \"/fake/datadir\""),
        "missing ExecStart: {content}"
    );
    assert!(
        !content.contains("ExecStart=\"/fake/bin/open-bitcoin\""),
        "unit should not supervise operator binary: {content}"
    );
    assert!(
        content.contains("Restart=on-failure"),
        "missing Restart: {content}"
    );
    assert!(
        content.contains("WantedBy=default.target"),
        "missing WantedBy: {content}"
    );
    assert!(
        content.contains("# Generated by Open Bitcoin"),
        "missing comment header: {content}"
    );
}

#[test]
fn unit_content_includes_config_path_when_provided() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoind");
    let datadir = Path::new("/fake/datadir");
    let config = Path::new("/fake/config/open-bitcoin.jsonc");

    // Act
    let content = generate_unit_content(binary, datadir, Some(config), None);

    // Assert
    assert!(
        content.contains("--config \"/fake/config/open-bitcoin.jsonc\""),
        "missing --config arg: {content}"
    );
}

#[test]
fn unit_content_includes_log_path_when_provided() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoind");
    let datadir = Path::new("/fake/datadir");
    let log_path = Path::new("/fake/logs/open-bitcoin.log");

    // Act
    let content = generate_unit_content(binary, datadir, None, Some(log_path));

    // Assert
    assert!(
        content.contains("StandardOutput=append:/fake/logs/open-bitcoin.log"),
        "missing StandardOutput append path: {content}"
    );
    assert!(
        content.contains("StandardError=append:/fake/logs/open-bitcoin.log"),
        "missing StandardError append path: {content}"
    );
}

// --- FakeServiceManager tests ---

#[test]
fn fake_manager_install_records_call() {
    // Arrange
    let manager = FakeServiceManager::unmanaged();
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoind"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: true,
    };

    // Act
    let result = manager.install(&request);

    // Assert
    assert!(result.is_ok(), "install should succeed: {result:?}");
    let calls = manager.recorded_calls.borrow();
    assert_eq!(calls.len(), 1);
    assert_eq!(calls[0], FakeServiceCall::Install { apply: true });
}

#[test]
fn fake_manager_status_returns_configured_state() {
    // Arrange
    let snapshot = ServiceStateSnapshot {
        state: ServiceLifecycleState::Unmanaged,
        maybe_enabled: Some(false),
        maybe_service_file_path: None,
        maybe_manager_diagnostics: None,
        maybe_log_path: None,
        maybe_log_path_unavailable_reason: Some("service not installed".to_string()),
    };
    let manager = FakeServiceManager::new(snapshot.clone());

    // Act
    let result = manager.status();

    // Assert
    assert!(result.is_ok());
    assert_eq!(result.unwrap(), snapshot);
    let calls = manager.recorded_calls.borrow();
    assert_eq!(calls.len(), 1);
    assert_eq!(calls[0], FakeServiceCall::Status);
}

// --- ServiceError display tests ---

#[test]
fn service_error_unsupported_platform_displays_reason() {
    // Arrange
    let error = ServiceError::UnsupportedPlatform {
        reason: "Windows is not supported".to_string(),
    };

    // Act
    let display = error.to_string();

    // Assert
    assert!(
        display.contains("Windows is not supported"),
        "missing reason: {display}"
    );
    assert!(
        display.contains("unsupported platform"),
        "missing prefix: {display}"
    );
}

#[test]
fn service_error_already_installed_displays_path() {
    // Arrange
    let path = PathBuf::from("/home/user/Library/LaunchAgents/org.open-bitcoin.node.plist");
    let error = ServiceError::AlreadyInstalled { path: path.clone() };

    // Act
    let display = error.to_string();

    // Assert
    assert!(
        display.contains(path.to_str().unwrap()),
        "missing path: {display}"
    );
    assert!(
        display.contains("already installed"),
        "missing prefix: {display}"
    );
}

#[test]
fn service_error_not_installed_points_to_preview_and_apply() {
    // Arrange
    let error = ServiceError::NotInstalled;

    // Act
    let display = error.to_string();

    // Assert
    assert!(
        display.contains("open-bitcoin service install"),
        "missing preview command: {display}"
    );
    assert!(
        display.contains("--apply"),
        "missing apply guidance: {display}"
    );
    assert!(
        !display.contains("--dry-run"),
        "stale dry-run hint: {display}"
    );
}

// --- LaunchdAdapter dry-run isolation tests ---

#[test]
fn launchd_install_dry_run_does_not_write_file() {
    // Arrange
    let test_dir = TestDirectory::new("launchd-dry-run");
    let home_dir = test_dir.path.clone();
    let adapter = LaunchdAdapter::new(home_dir.clone());
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoind"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: false,
    };

    // Act
    let result = adapter.install(&request);

    // Assert
    assert!(result.is_ok(), "dry-run should succeed: {result:?}");
    let outcome = result.unwrap();
    assert!(outcome.dry_run, "outcome should be dry_run=true");
    let plist_path = home_dir
        .join("Library")
        .join("LaunchAgents")
        .join("org.open-bitcoin.node.plist");
    assert!(
        !plist_path.exists(),
        "plist file must NOT exist after dry-run"
    );
}

#[test]
fn launchd_install_dry_run_lists_enable_and_bootstrap_commands() {
    // Arrange
    let test_dir = TestDirectory::new("launchd-dry-run-commands");
    let adapter = LaunchdAdapter::new(test_dir.path.clone());
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoind"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: false,
    };

    // Act
    let outcome = adapter.install(&request).expect("launchd dry-run install");

    // Assert
    assert_eq!(outcome.commands_that_would_run.len(), 2);
    assert!(
        outcome.commands_that_would_run[0].starts_with("launchctl enable gui/"),
        "missing launchctl enable preview: {:?}",
        outcome.commands_that_would_run
    );
    assert!(
        outcome.commands_that_would_run[1].starts_with("launchctl bootstrap gui/"),
        "missing launchctl bootstrap preview: {:?}",
        outcome.commands_that_would_run
    );
}

// --- SystemdAdapter dry-run isolation tests ---

#[test]
fn systemd_install_dry_run_does_not_write_file() {
    // Arrange
    let test_dir = TestDirectory::new("systemd-dry-run");
    let home_dir = test_dir.path.clone();
    let adapter = SystemdAdapter::new(home_dir.clone());
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoind"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: false,
    };

    // Act
    let result = adapter.install(&request);

    // Assert
    assert!(result.is_ok(), "dry-run should succeed: {result:?}");
    let outcome = result.unwrap();
    assert!(outcome.dry_run, "outcome should be dry_run=true");
    let unit_path = home_dir
        .join(".config")
        .join("systemd")
        .join("user")
        .join("open-bitcoin-node.service");
    assert!(
        !unit_path.exists(),
        "unit file must NOT exist after dry-run"
    );
}

#[test]
fn systemd_install_dry_run_lists_reload_and_enable_commands() {
    // Arrange
    let test_dir = TestDirectory::new("systemd-dry-run-commands");
    let adapter = SystemdAdapter::new(test_dir.path.clone());
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoind"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: false,
    };

    // Act
    let outcome = adapter.install(&request).expect("systemd dry-run install");

    // Assert
    assert_eq!(
        outcome.commands_that_would_run,
        vec![
            "systemctl --user daemon-reload".to_string(),
            "systemctl --user enable open-bitcoin-node.service".to_string(),
        ]
    );
}

#[test]
fn launchd_disabled_services_parser_detects_enabled_and_disabled_entries() {
    // Arrange
    let disabled_output = r#"
{
    "org.open-bitcoin.node" => true
}
"#;
    let enabled_output = r#"
{
    "org.open-bitcoin.node" => false
}
"#;

    // Act / Assert
    assert_eq!(
        parse_launchd_disabled_services(disabled_output, "org.open-bitcoin.node"),
        Some(false)
    );
    assert_eq!(
        parse_launchd_disabled_services(enabled_output, "org.open-bitcoin.node"),
        Some(true)
    );
}

#[test]
fn launchd_log_path_parser_reads_standard_out_path() {
    // Arrange
    let plist = r#"
<dict>
    <key>StandardOutPath</key>
    <string>/fake/logs/open-bitcoin.log</string>
    <key>StandardErrorPath</key>
    <string>/fake/logs/open-bitcoin.log</string>
</dict>
"#;

    // Act
    let maybe_log_path = parse_launchd_log_path(plist);

    // Assert
    assert_eq!(
        maybe_log_path,
        Some(PathBuf::from("/fake/logs/open-bitcoin.log"))
    );
}

#[test]
fn systemd_enabled_state_parser_classifies_common_states() {
    // Arrange / Act / Assert
    assert_eq!(parse_systemd_enabled_state("enabled\n"), Some(true));
    assert_eq!(parse_systemd_enabled_state("disabled\n"), Some(false));
    assert_eq!(parse_systemd_enabled_state("masked\n"), Some(false));
}

#[test]
fn systemd_log_path_parser_reads_append_path() {
    // Arrange
    let unit = "\
[Service]\n\
StandardOutput=append:/fake/logs/open-bitcoin.log\n\
StandardError=append:/fake/logs/open-bitcoin.log\n";

    // Act
    let maybe_log_path = parse_systemd_log_path(unit);

    // Assert
    assert_eq!(
        maybe_log_path,
        Some(PathBuf::from("/fake/logs/open-bitcoin.log"))
    );
}

#[test]
fn launchd_start_stop_restart_commands_are_user_scope() {
    // Arrange
    let plist_path = Path::new("/fake/home/Library/LaunchAgents/org.open-bitcoin.node.plist");
    let uid = 501;

    // Act
    let commands = [
        launchd_start_command(uid, plist_path),
        launchd_stop_command(uid),
        launchd_restart_command(uid),
    ];

    // Assert
    assert_eq!(
        commands[0],
        "launchctl bootstrap gui/501 /fake/home/Library/LaunchAgents/org.open-bitcoin.node.plist"
    );
    assert_eq!(
        commands[1],
        "launchctl bootout gui/501/org.open-bitcoin.node"
    );
    assert_eq!(
        commands[2],
        "launchctl kickstart -k gui/501/org.open-bitcoin.node"
    );
    for command in commands {
        assert!(
            !command.contains("sudo")
                && !command.contains("/Library/LaunchDaemons")
                && !command.contains("bitcoind.service")
                && !command.contains("bitcoin-knots"),
            "launchd lifecycle command must stay user-scope: {command}"
        );
    }
}

#[test]
fn launchd_start_stop_restart_missing_plist_returns_not_installed() {
    // Arrange
    let test_dir = TestDirectory::new("launchd-missing-lifecycle");
    let adapter = LaunchdAdapter::new(test_dir.path.clone());

    // Act
    let start_result = adapter.start(&ServiceStartRequest);
    let stop_result = adapter.stop(&ServiceStopRequest);
    let restart_result = adapter.restart(&ServiceRestartRequest);

    // Assert
    assert!(
        matches!(start_result, Err(ServiceError::NotInstalled)),
        "missing launchd plist should block start: {start_result:?}"
    );
    assert!(
        matches!(stop_result, Err(ServiceError::NotInstalled)),
        "missing launchd plist should block stop: {stop_result:?}"
    );
    assert!(
        matches!(restart_result, Err(ServiceError::NotInstalled)),
        "missing launchd plist should block restart: {restart_result:?}"
    );
}

#[test]
fn systemd_start_stop_restart_commands_are_user_scope() {
    // Arrange / Act
    let commands = [
        systemd_start_command(),
        systemd_stop_command(),
        systemd_restart_command(),
    ];

    // Assert
    assert_eq!(
        commands[0],
        "systemctl --user start open-bitcoin-node.service"
    );
    assert_eq!(
        commands[1],
        "systemctl --user stop open-bitcoin-node.service"
    );
    assert_eq!(
        commands[2],
        "systemctl --user restart open-bitcoin-node.service"
    );
    for command in commands {
        assert!(
            !command.contains("sudo")
                && !command.contains("/etc/systemd/system")
                && !command.contains("bitcoind.service")
                && !command.contains("bitcoin-knots"),
            "systemd lifecycle command must stay user-scope: {command}"
        );
    }
}

#[test]
fn systemd_start_stop_restart_missing_unit_returns_not_installed() {
    // Arrange
    let test_dir = TestDirectory::new("systemd-missing-lifecycle");
    let adapter = SystemdAdapter::new(test_dir.path.clone());

    // Act
    let start_result = adapter.start(&ServiceStartRequest);
    let stop_result = adapter.stop(&ServiceStopRequest);
    let restart_result = adapter.restart(&ServiceRestartRequest);

    // Assert
    assert!(
        matches!(start_result, Err(ServiceError::NotInstalled)),
        "missing systemd unit should block start: {start_result:?}"
    );
    assert!(
        matches!(stop_result, Err(ServiceError::NotInstalled)),
        "missing systemd unit should block stop: {stop_result:?}"
    );
    assert!(
        matches!(restart_result, Err(ServiceError::NotInstalled)),
        "missing systemd unit should block restart: {restart_result:?}"
    );
}

// --- execute_service_command tests ---

fn preview_install_outcome() -> ServiceCommandOutcome {
    ServiceCommandOutcome {
        dry_run: true,
        description: "fake preview".to_string(),
        maybe_file_path: Some(PathBuf::from(
            "/fake/home/Library/LaunchAgents/org.open-bitcoin.node.plist",
        )),
        maybe_file_content: Some("fake generated content".to_string()),
        commands_that_would_run: vec![
            "launchctl enable gui/501/org.open-bitcoin.node".to_string(),
            "launchctl bootstrap gui/501 /fake/home/Library/LaunchAgents/org.open-bitcoin.node.plist"
                .to_string(),
        ],
    }
}

#[test]
fn parsing_service_start_selects_service_start_command() {
    // Arrange / Act
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "start"])
        .expect("service start should parse");

    // Assert
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };
    assert_eq!(service_args.command, ServiceCommand::Start);
    assert!(
        !service_args.apply,
        "service start must not require --apply to parse"
    );
}

#[test]
fn parsing_service_stop_selects_service_stop_command() {
    // Arrange / Act
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "stop"])
        .expect("service stop should parse");

    // Assert
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };
    assert_eq!(service_args.command, ServiceCommand::Stop);
    assert!(
        !service_args.apply,
        "service stop must not require --apply to parse"
    );
}

#[test]
fn parsing_service_restart_selects_service_restart_command() {
    // Arrange / Act
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "restart"])
        .expect("service restart should parse");

    // Assert
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };
    assert_eq!(service_args.command, ServiceCommand::Restart);
    assert!(
        !service_args.apply,
        "service restart must not require --apply to parse"
    );
}

#[test]
fn fake_manager_service_start_stop_restart_records_call_order() {
    // Arrange
    let manager = FakeServiceManager::unmanaged();

    // Act
    let start_result = manager.start(&ServiceStartRequest);
    let stop_result = manager.stop(&ServiceStopRequest);
    let restart_result = manager.restart(&ServiceRestartRequest);

    // Assert
    assert!(
        start_result.is_ok(),
        "start should succeed: {start_result:?}"
    );
    assert!(stop_result.is_ok(), "stop should succeed: {stop_result:?}");
    assert!(
        restart_result.is_ok(),
        "restart should succeed: {restart_result:?}"
    );
    assert_eq!(
        manager.recorded_calls.borrow().as_slice(),
        &[
            FakeServiceCall::Start,
            FakeServiceCall::Stop,
            FakeServiceCall::Restart
        ]
    );
}

#[test]
fn execute_service_command_service_start_calls_manager_and_renders_commands() {
    // Arrange
    let mut manager = FakeServiceManager::unmanaged();
    manager.start_commands = vec!["systemctl --user start open-bitcoin-node.service".to_string()];
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "start"])
        .expect("service start should parse");
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success
    );
    assert_eq!(
        manager.recorded_calls.borrow().as_slice(),
        &[FakeServiceCall::Start]
    );
    assert!(
        outcome
            .stdout
            .text
            .contains("systemctl --user start open-bitcoin-node.service"),
        "stdout should contain start command: {}",
        outcome.stdout.text
    );
    assert!(
        !outcome.stdout.text.contains("Dry run"),
        "start should be effectful rather than a dry run: {}",
        outcome.stdout.text
    );
}

#[test]
fn execute_service_command_service_stop_calls_manager_and_renders_commands() {
    // Arrange
    let mut manager = FakeServiceManager::unmanaged();
    manager.stop_commands = vec!["systemctl --user stop open-bitcoin-node.service".to_string()];
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "stop"])
        .expect("service stop should parse");
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success
    );
    assert_eq!(
        manager.recorded_calls.borrow().as_slice(),
        &[FakeServiceCall::Stop]
    );
    assert!(
        outcome
            .stdout
            .text
            .contains("systemctl --user stop open-bitcoin-node.service"),
        "stdout should contain stop command: {}",
        outcome.stdout.text
    );
    assert!(
        !outcome.stdout.text.contains("Dry run"),
        "stop should be effectful rather than a dry run: {}",
        outcome.stdout.text
    );
}

#[test]
fn execute_service_command_service_restart_calls_manager_and_renders_commands() {
    // Arrange
    let mut manager = FakeServiceManager::unmanaged();
    manager.restart_commands =
        vec!["systemctl --user restart open-bitcoin-node.service".to_string()];
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "restart"])
        .expect("service restart should parse");
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success
    );
    assert_eq!(
        manager.recorded_calls.borrow().as_slice(),
        &[FakeServiceCall::Restart]
    );
    assert!(
        outcome
            .stdout
            .text
            .contains("systemctl --user restart open-bitcoin-node.service"),
        "stdout should contain restart command: {}",
        outcome.stdout.text
    );
    assert!(
        !outcome.stdout.text.contains("Dry run"),
        "restart should be effectful rather than a dry run: {}",
        outcome.stdout.text
    );
}

#[test]
fn execute_service_command_service_preview_calls_install_dry_run() {
    // Arrange
    let mut manager = FakeServiceManager::unmanaged();
    manager.install_outcome = Some(preview_install_outcome());
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "preview"])
        .expect("service preview should parse");
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success
    );
    assert_eq!(
        manager.recorded_calls.borrow().as_slice(),
        &[FakeServiceCall::Install { apply: false }]
    );
}

#[test]
fn execute_service_command_service_preview_renders_install_preview_output() {
    // Arrange
    let mut manager = FakeServiceManager::unmanaged();
    manager.install_outcome = Some(preview_install_outcome());
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "preview"])
        .expect("service preview should parse");
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    let stdout = &outcome.stdout.text;
    assert!(stdout.contains("Dry run"), "missing dry-run text: {stdout}");
    assert!(
        stdout.contains("Would write"),
        "missing file path preview: {stdout}"
    );
    assert!(
        stdout.contains("Generated content"),
        "missing generated content: {stdout}"
    );
    assert!(
        stdout.contains("Commands"),
        "missing manager commands: {stdout}"
    );
    assert!(
        stdout.contains("Scope: user-level"),
        "missing user-level scope: {stdout}"
    );
}

#[test]
fn execute_service_command_service_preview_apply_rejects_without_manager_call() {
    // Arrange
    let manager = FakeServiceManager::unmanaged();
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "preview", "--apply"])
        .expect("service preview --apply should parse before dispatcher rejection");
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Failure(1)
    );
    assert_eq!(
        outcome.stderr.text,
        "service preview is always side-effect-free; remove --apply"
    );
    assert!(
        manager.recorded_calls.borrow().is_empty(),
        "preview --apply must not call the manager"
    );
}

#[test]
fn execute_service_command_service_install_without_apply_still_records_dry_run() {
    // Arrange
    let manager = FakeServiceManager::unmanaged();
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "install"])
        .expect("service install should parse");
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success
    );
    assert_eq!(
        manager.recorded_calls.borrow().as_slice(),
        &[FakeServiceCall::Install { apply: false }]
    );
}

#[test]
fn execute_service_command_install_dry_run_shows_dry_run_output() {
    // Arrange
    let manager = FakeServiceManager::unmanaged();
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "install"]).unwrap();
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success,
        "dry-run install should succeed"
    );
    let stdout = &outcome.stdout.text;
    assert!(
        stdout.contains("Dry run") || stdout.contains("dry run") || stdout.contains("dry-run"),
        "stdout should contain dry run indicator: {stdout}"
    );
}

#[test]
fn execute_service_command_install_already_installed_returns_failure() {
    // Arrange
    let mut manager = FakeServiceManager::unmanaged();
    manager.install_error = Some(ServiceError::AlreadyInstalled {
        path: PathBuf::from("/fake/LaunchAgents/org.open-bitcoin.node.plist"),
    });
    let cli =
        OperatorCli::try_parse_from(["open-bitcoin", "service", "install", "--apply"]).unwrap();
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Failure(1),
        "already installed should return failure"
    );
    assert!(
        outcome.stderr.text.contains("already installed"),
        "stderr should contain 'already installed': {}",
        outcome.stderr.text
    );
}

#[test]
fn execute_service_command_enable_returns_success_with_output() {
    // Arrange
    let manager = FakeServiceManager::unmanaged();
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "enable"]).unwrap();
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success,
        "enable should succeed"
    );
    assert!(
        !outcome.stdout.text.is_empty(),
        "enable should produce output"
    );
}

#[test]
fn execute_service_command_uninstall_dry_run_succeeds() {
    // Arrange
    let manager = FakeServiceManager::unmanaged();
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "uninstall"]).unwrap();
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success,
        "dry-run uninstall with fake manager should succeed"
    );
}

#[test]
fn parsing_service_install_with_apply_flag_sets_apply_true() {
    // Arrange / Act
    let cli =
        OperatorCli::try_parse_from(["open-bitcoin", "service", "install", "--apply"]).unwrap();

    // Assert
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };
    assert!(
        service_args.apply,
        "apply flag should be true when --apply is passed"
    );
}

#[test]
fn parsing_service_install_without_apply_flag_sets_apply_false() {
    // Arrange / Act
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "install"]).unwrap();

    // Assert
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };
    assert!(!service_args.apply, "apply flag should be false by default");
}

#[test]
fn execute_service_command_install_dry_run_shows_scope() {
    // Arrange
    let manager = FakeServiceManager::unmanaged();
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "install"]).unwrap();
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success
    );
    let stdout = &outcome.stdout.text;
    assert!(
        stdout.contains("user-level") || stdout.contains("Scope"),
        "stdout should mention user-level scope: {stdout}"
    );
}

#[test]
fn execute_service_command_status_surfaces_enabled_and_running_flags() {
    // Arrange
    let snapshot = ServiceStateSnapshot {
        state: ServiceLifecycleState::Failed,
        maybe_enabled: Some(true),
        maybe_service_file_path: Some(PathBuf::from("/tmp/open-bitcoin-node.service")),
        maybe_manager_diagnostics: Some("systemctl is-active=failed".to_string()),
        maybe_log_path: Some(PathBuf::from("/tmp/logs/open-bitcoin.log")),
        maybe_log_path_unavailable_reason: None,
    };
    let manager = FakeServiceManager::new(snapshot);
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "status"]).unwrap();
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success
    );
    assert!(outcome.stdout.text.contains("service: failed"));
    assert!(outcome.stdout.text.contains("enabled: true"));
    assert!(outcome.stdout.text.contains("running: false"));
    assert!(
        outcome
            .stdout
            .text
            .contains("logs: /tmp/logs/open-bitcoin.log")
    );
}

#[test]
fn phase63_service_lifecycle_rendering_direct_status_labels() {
    // Arrange
    let cases = [
        (
            ServiceStateSnapshot {
                state: ServiceLifecycleState::Unmanaged,
                maybe_enabled: None,
                maybe_service_file_path: None,
                maybe_manager_diagnostics: None,
                maybe_log_path: None,
                maybe_log_path_unavailable_reason: Some("service not installed".to_string()),
            },
            "service: unmanaged",
        ),
        (
            ServiceStateSnapshot {
                state: ServiceLifecycleState::Installed,
                maybe_enabled: Some(true),
                maybe_service_file_path: Some(PathBuf::from("/tmp/open-bitcoin-node.service")),
                maybe_manager_diagnostics: None,
                maybe_log_path: Some(PathBuf::from("/tmp/logs/open-bitcoin.log")),
                maybe_log_path_unavailable_reason: None,
            },
            "service: installed-stopped",
        ),
        (
            ServiceStateSnapshot {
                state: ServiceLifecycleState::Running,
                maybe_enabled: Some(false),
                maybe_service_file_path: Some(PathBuf::from("/tmp/open-bitcoin-node.service")),
                maybe_manager_diagnostics: Some("running while startup is disabled".to_string()),
                maybe_log_path: Some(PathBuf::from("/tmp/logs/open-bitcoin.log")),
                maybe_log_path_unavailable_reason: None,
            },
            "service: running",
        ),
        (
            ServiceStateSnapshot {
                state: ServiceLifecycleState::Failed,
                maybe_enabled: Some(true),
                maybe_service_file_path: Some(PathBuf::from("/tmp/open-bitcoin-node.service")),
                maybe_manager_diagnostics: Some("systemctl is-active=failed".to_string()),
                maybe_log_path: Some(PathBuf::from("/tmp/logs/open-bitcoin.log")),
                maybe_log_path_unavailable_reason: None,
            },
            "service: failed",
        ),
        (
            ServiceStateSnapshot {
                state: ServiceLifecycleState::Stopped,
                maybe_enabled: Some(false),
                maybe_service_file_path: Some(PathBuf::from("/tmp/open-bitcoin-node.service")),
                maybe_manager_diagnostics: None,
                maybe_log_path: Some(PathBuf::from("/tmp/logs/open-bitcoin.log")),
                maybe_log_path_unavailable_reason: None,
            },
            "service: disabled",
        ),
    ];

    // Act
    let actual = cases
        .iter()
        .map(|(snapshot, _)| first_status_line(snapshot.clone()))
        .collect::<Vec<_>>();

    // Assert
    assert_eq!(
        actual,
        cases
            .iter()
            .map(|(_, expected)| expected.to_string())
            .collect::<Vec<_>>()
    );

    struct ErrorStatusManager;
    impl ServiceManager for ErrorStatusManager {
        fn install(
            &self,
            _request: &ServiceInstallRequest,
        ) -> Result<ServiceCommandOutcome, ServiceError> {
            Err(ServiceError::UnsupportedPlatform {
                reason: "not used by this test".to_string(),
            })
        }

        fn uninstall(
            &self,
            _request: &crate::operator::service::ServiceUninstallRequest,
        ) -> Result<ServiceCommandOutcome, ServiceError> {
            Err(ServiceError::UnsupportedPlatform {
                reason: "not used by this test".to_string(),
            })
        }

        fn enable(
            &self,
            _request: &crate::operator::service::ServiceEnableRequest,
        ) -> Result<ServiceCommandOutcome, ServiceError> {
            Err(ServiceError::UnsupportedPlatform {
                reason: "not used by this test".to_string(),
            })
        }

        fn disable(
            &self,
            _request: &crate::operator::service::ServiceDisableRequest,
        ) -> Result<ServiceCommandOutcome, ServiceError> {
            Err(ServiceError::UnsupportedPlatform {
                reason: "not used by this test".to_string(),
            })
        }

        fn status(&self) -> Result<ServiceStateSnapshot, ServiceError> {
            Err(ServiceError::UnsupportedPlatform {
                reason: "system service manager unavailable".to_string(),
            })
        }
    }

    let manager = ErrorStatusManager;
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "status"])
        .expect("service status should parse");
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    let unavailable = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );
    assert_eq!(
        unavailable.exit_code,
        crate::operator::runtime::OperatorExitCode::Success
    );
    assert!(
        unavailable
            .stdout
            .text
            .starts_with("service: unavailable-manager")
    );
    assert!(
        unavailable
            .stdout
            .text
            .contains("diagnostics: unsupported platform: system service manager unavailable")
    );
}

fn first_status_line(snapshot: ServiceStateSnapshot) -> String {
    let manager = FakeServiceManager::new(snapshot);
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "status"])
        .expect("service status should parse");
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success
    );
    outcome
        .stdout
        .text
        .lines()
        .next()
        .expect("service status output should have a first line")
        .to_string()
}

#[test]
fn execute_service_command_status_surfaces_unavailable_log_path_reason() {
    // Arrange
    let snapshot = ServiceStateSnapshot {
        state: ServiceLifecycleState::Installed,
        maybe_enabled: Some(false),
        maybe_service_file_path: Some(PathBuf::from("/tmp/open-bitcoin-node.service")),
        maybe_manager_diagnostics: Some("systemctl is-enabled=false".to_string()),
        maybe_log_path: None,
        maybe_log_path_unavailable_reason: Some(
            "installed unit routes service output to journald".to_string(),
        ),
    };
    let manager = FakeServiceManager::new(snapshot);
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "status"]).unwrap();
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success
    );
    assert!(
        outcome
            .stdout
            .text
            .contains("logs: Unavailable: installed unit routes service output to journald")
    );
}

#[test]
fn execute_service_command_status_unmanaged_surfaces_preview_hint() {
    // Arrange
    let snapshot = ServiceStateSnapshot {
        state: ServiceLifecycleState::Unmanaged,
        maybe_enabled: Some(false),
        maybe_service_file_path: None,
        maybe_manager_diagnostics: Some(
            "unmanaged — run `open-bitcoin service install` to preview what would be created"
                .to_string(),
        ),
        maybe_log_path: None,
        maybe_log_path_unavailable_reason: Some("service not installed".to_string()),
    };
    let manager = FakeServiceManager::new(snapshot);
    let cli = OperatorCli::try_parse_from(["open-bitcoin", "service", "status"]).unwrap();
    let crate::operator::OperatorCommand::Service(service_args) = &cli.command else {
        panic!("expected Service command");
    };

    // Act
    let outcome = execute_service_command(
        service_args,
        PathBuf::from("/fake/bin/open-bitcoind"),
        PathBuf::from("/fake/datadir"),
        None,
        None,
        &manager,
    );

    // Assert
    assert_eq!(
        outcome.exit_code,
        crate::operator::runtime::OperatorExitCode::Success
    );
    assert!(
        outcome
            .stdout
            .text
            .contains("hint: run `open-bitcoin service install` to preview what would be created")
    );
    assert!(!outcome.stdout.text.contains("--dry-run"));
}

#[test]
fn launchd_status_unmanaged_diagnostics_use_preview_contract() {
    // Arrange
    let test_dir = TestDirectory::new("launchd-unmanaged-preview-hint");
    let adapter = LaunchdAdapter::new(test_dir.path.clone());

    // Act
    let snapshot = adapter.status().expect("launchd unmanaged status");

    // Assert
    assert_eq!(snapshot.state, ServiceLifecycleState::Unmanaged);
    let diagnostics = snapshot
        .maybe_manager_diagnostics
        .expect("launchd unmanaged diagnostics");
    assert!(diagnostics.contains("open-bitcoin service install"));
    assert!(diagnostics.contains("preview"));
    assert!(!diagnostics.contains("--dry-run"));
}

#[test]
fn systemd_status_unmanaged_diagnostics_use_preview_contract() {
    // Arrange
    let test_dir = TestDirectory::new("systemd-unmanaged-preview-hint");
    let adapter = SystemdAdapter::new(test_dir.path.clone());

    // Act
    let snapshot = adapter.status().expect("systemd unmanaged status");

    // Assert
    assert_eq!(snapshot.state, ServiceLifecycleState::Unmanaged);
    let diagnostics = snapshot
        .maybe_manager_diagnostics
        .expect("systemd unmanaged diagnostics");
    assert!(diagnostics.contains("open-bitcoin service install"));
    assert!(diagnostics.contains("preview"));
    assert!(!diagnostics.contains("--dry-run"));
}
