// Parity breadcrumbs:
// - none: Open Bitcoin-only support/infrastructure; no direct Bitcoin Knots source anchor identified.

//! Tests for service lifecycle generators, FakeServiceManager, and dry-run safety.

use std::{
    path::{Path, PathBuf},
    sync::atomic::{AtomicU64, Ordering},
};

use crate::operator::service::{
    ServiceError, ServiceInstallRequest, ServiceLifecycleState, ServiceManager,
    ServiceStateSnapshot,
    fake::{FakeServiceCall, FakeServiceManager},
    launchd::{LaunchdAdapter, generate_plist_content},
    systemd::{SystemdAdapter, generate_unit_content},
};

static NEXT_TEST_DIRECTORY_ID: AtomicU64 = AtomicU64::new(0);

/// RAII temp directory for isolation in service tests.
struct TestDirectory {
    path: PathBuf,
}

impl TestDirectory {
    fn new(label: &str) -> Self {
        let directory = std::env::temp_dir().join(format!(
            "open-bitcoin-service-tests-{label}-{}",
            NEXT_TEST_DIRECTORY_ID.fetch_add(1, Ordering::Relaxed)
        ));
        std::fs::create_dir_all(&directory).expect("test directory");
        Self { path: directory }
    }
}

impl Drop for TestDirectory {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.path);
    }
}

// --- Plist generator tests ---

#[test]
fn plist_content_contains_required_fields() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoin");
    let datadir = Path::new("/fake/datadir");

    // Act
    let content = generate_plist_content("org.open-bitcoin.node", binary, datadir, None, None);

    // Assert
    assert!(
        content.contains("<string>org.open-bitcoin.node</string>"),
        "missing label: {content}"
    );
    assert!(
        content.contains("<string>/fake/bin/open-bitcoin</string>"),
        "missing binary path: {content}"
    );
    assert!(
        content.contains("<string>/fake/datadir</string>"),
        "missing datadir: {content}"
    );
    assert!(content.contains("<true/>"), "missing KeepAlive or RunAtLoad: {content}");
    assert!(
        content.contains("Generated by Open Bitcoin"),
        "missing comment header: {content}"
    );
}

#[test]
fn plist_content_includes_config_path_when_provided() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoin");
    let datadir = Path::new("/fake/datadir");
    let config = Path::new("/fake/config/open-bitcoin.jsonc");

    // Act
    let content =
        generate_plist_content("org.open-bitcoin.node", binary, datadir, Some(config), None);

    // Assert
    assert!(
        content.contains("<string>--config</string>"),
        "missing --config arg: {content}"
    );
    assert!(
        content.contains("<string>/fake/config/open-bitcoin.jsonc</string>"),
        "missing config path: {content}"
    );
}

#[test]
fn plist_content_includes_log_paths_when_provided() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoin");
    let datadir = Path::new("/fake/datadir");
    let log = Path::new("/fake/logs/open-bitcoin.log");

    // Act
    let content =
        generate_plist_content("org.open-bitcoin.node", binary, datadir, None, Some(log));

    // Assert
    assert!(
        content.contains("StandardOutPath"),
        "missing StandardOutPath: {content}"
    );
    assert!(
        content.contains("StandardErrorPath"),
        "missing StandardErrorPath: {content}"
    );
    assert!(
        content.contains("/fake/logs/open-bitcoin.log"),
        "missing log path: {content}"
    );
}

// --- Unit file generator tests ---

#[test]
fn unit_content_contains_required_fields() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoin");
    let datadir = Path::new("/fake/datadir");

    // Act
    let content = generate_unit_content(binary, datadir, None);

    // Assert
    assert!(content.contains("[Unit]"), "missing [Unit]: {content}");
    assert!(content.contains("[Service]"), "missing [Service]: {content}");
    assert!(content.contains("[Install]"), "missing [Install]: {content}");
    assert!(
        content.contains("ExecStart=/fake/bin/open-bitcoin --datadir /fake/datadir"),
        "missing ExecStart: {content}"
    );
    assert!(
        content.contains("Restart=on-failure"),
        "missing Restart: {content}"
    );
    assert!(
        content.contains("WantedBy=default.target"),
        "missing WantedBy: {content}"
    );
    assert!(
        content.contains("# Generated by Open Bitcoin"),
        "missing comment header: {content}"
    );
}

#[test]
fn unit_content_includes_config_path_when_provided() {
    // Arrange
    let binary = Path::new("/fake/bin/open-bitcoin");
    let datadir = Path::new("/fake/datadir");
    let config = Path::new("/fake/config/open-bitcoin.jsonc");

    // Act
    let content = generate_unit_content(binary, datadir, Some(config));

    // Assert
    assert!(
        content.contains("--config /fake/config/open-bitcoin.jsonc"),
        "missing --config arg: {content}"
    );
}

// --- FakeServiceManager tests ---

#[test]
fn fake_manager_install_records_call() {
    // Arrange
    let manager = FakeServiceManager::unmanaged();
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoin"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: true,
    };

    // Act
    let result = manager.install(&request);

    // Assert
    assert!(result.is_ok(), "install should succeed: {result:?}");
    let calls = manager.recorded_calls.borrow();
    assert_eq!(calls.len(), 1);
    assert_eq!(calls[0], FakeServiceCall::Install { apply: true });
}

#[test]
fn fake_manager_status_returns_configured_state() {
    // Arrange
    let snapshot = ServiceStateSnapshot {
        state: ServiceLifecycleState::Unmanaged,
        maybe_service_file_path: None,
        maybe_manager_diagnostics: None,
        maybe_log_path: None,
    };
    let manager = FakeServiceManager::new(snapshot.clone());

    // Act
    let result = manager.status();

    // Assert
    assert!(result.is_ok());
    assert_eq!(result.unwrap(), snapshot);
    let calls = manager.recorded_calls.borrow();
    assert_eq!(calls.len(), 1);
    assert_eq!(calls[0], FakeServiceCall::Status);
}

// --- ServiceError display tests ---

#[test]
fn service_error_unsupported_platform_displays_reason() {
    // Arrange
    let error = ServiceError::UnsupportedPlatform {
        reason: "Windows is not supported".to_string(),
    };

    // Act
    let display = error.to_string();

    // Assert
    assert!(
        display.contains("Windows is not supported"),
        "missing reason: {display}"
    );
    assert!(
        display.contains("unsupported platform"),
        "missing prefix: {display}"
    );
}

#[test]
fn service_error_already_installed_displays_path() {
    // Arrange
    let path = PathBuf::from("/home/user/Library/LaunchAgents/org.open-bitcoin.node.plist");
    let error = ServiceError::AlreadyInstalled { path: path.clone() };

    // Act
    let display = error.to_string();

    // Assert
    assert!(
        display.contains(path.to_str().unwrap()),
        "missing path: {display}"
    );
    assert!(
        display.contains("already installed"),
        "missing prefix: {display}"
    );
}

// --- LaunchdAdapter dry-run isolation tests ---

#[test]
fn launchd_install_dry_run_does_not_write_file() {
    // Arrange
    let test_dir = TestDirectory::new("launchd-dry-run");
    let home_dir = test_dir.path.clone();
    let adapter = LaunchdAdapter::new(home_dir.clone());
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoin"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: false,
    };

    // Act
    let result = adapter.install(&request);

    // Assert
    assert!(result.is_ok(), "dry-run should succeed: {result:?}");
    let outcome = result.unwrap();
    assert!(outcome.dry_run, "outcome should be dry_run=true");
    let plist_path = home_dir
        .join("Library")
        .join("LaunchAgents")
        .join("org.open-bitcoin.node.plist");
    assert!(
        !plist_path.exists(),
        "plist file must NOT exist after dry-run"
    );
}

// --- SystemdAdapter dry-run isolation tests ---

#[test]
fn systemd_install_dry_run_does_not_write_file() {
    // Arrange
    let test_dir = TestDirectory::new("systemd-dry-run");
    let home_dir = test_dir.path.clone();
    let adapter = SystemdAdapter::new(home_dir.clone());
    let request = ServiceInstallRequest {
        binary_path: PathBuf::from("/fake/bin/open-bitcoin"),
        data_dir: PathBuf::from("/fake/datadir"),
        maybe_config_path: None,
        maybe_log_path: None,
        apply: false,
    };

    // Act
    let result = adapter.install(&request);

    // Assert
    assert!(result.is_ok(), "dry-run should succeed: {result:?}");
    let outcome = result.unwrap();
    assert!(outcome.dry_run, "outcome should be dry_run=true");
    let unit_path = home_dir
        .join(".config")
        .join("systemd")
        .join("user")
        .join("open-bitcoin-node.service");
    assert!(
        !unit_path.exists(),
        "unit file must NOT exist after dry-run"
    );
}
