export const NODE = "packages/open-bitcoin-node/src/";
export const RPC = "packages/open-bitcoin-rpc/src/";
export const CLI = "packages/open-bitcoin-cli/src/";
export const PHASE = ".planning/phases/159-authenticated-basic-filter-and-index-rpcs/";
export const DOC = "docs/parity/catalog/basic-compact-filters.md";
export const SURFACE = "v2-5-authenticated-basic-filter-and-index-rpcs";
export const NEW_RUST: string[] = [
  "packages/open-bitcoin-node/src/chainstate/validation_history.rs",
  "packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs",
  "packages/open-bitcoin-node/src/chainstate/validation_history/tests/fixtures.rs",
  "packages/open-bitcoin-node/src/storage/validation_history.rs",
  "packages/open-bitcoin-node/src/storage/validation_history/tests.rs",
  "packages/open-bitcoin-node/src/chainstate/validation_history/tests/coverage.rs",
  "packages/open-bitcoin-node/src/chainstate/validation_history/tests/network.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs",
  "packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/owner.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/interleavings.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/validation_history.rs",
  "packages/open-bitcoin-node/src/network/validation_history.rs",
  "packages/open-bitcoin-node/src/sync/runtime_state/tests.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/filters/query.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/filters/query/tests.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/validation_history.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs",
  "packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc.rs",
  "packages/open-bitcoin-rpc/src/context/filter_index.rs",
  "packages/open-bitcoin-rpc/src/dispatch/filter_index.rs",
  "packages/open-bitcoin-rpc/src/dispatch/filter_index/tests.rs",
  "packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/failures.rs",
  "packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/retention.rs",
  "packages/open-bitcoin-rpc/src/http/filter_index.rs",
  "packages/open-bitcoin-rpc/src/http/tests/filter_index.rs",
  "packages/open-bitcoin-rpc/src/http/tests/filter_index/fixtures.rs",
  "packages/open-bitcoin-rpc/src/method/filter_index.rs",
  "packages/open-bitcoin-rpc/src/method/filter_index/normalize.rs",
  "packages/open-bitcoin-rpc/src/method/filter_index/tests.rs"
];
export const SOURCE_FILES: string[] = [
  NODE + "storage/fjall_store/filters/tests/append/admission.rs",
  CLI + "main.rs", CLI + "lib.rs", CLI + "client.rs", CLI + "client/tests.rs", CLI + "args.rs", CLI + "args/tests.rs",
  "packages/open-bitcoin-node/src/chainstate/validation_history.rs",
  "packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs",
  "packages/open-bitcoin-node/src/chainstate/validation_history/tests/fixtures.rs",
  "packages/open-bitcoin-node/src/storage/validation_history.rs",
  "packages/open-bitcoin-node/src/storage/validation_history/tests.rs",
  "packages/open-bitcoin-node/src/chainstate/validation_history/tests/coverage.rs",
  "packages/open-bitcoin-node/src/chainstate/validation_history/tests/network.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs",
  "packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/owner.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/interleavings.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/validation_history.rs",
  "packages/open-bitcoin-node/src/network/validation_history.rs",
  "packages/open-bitcoin-node/src/sync/runtime_state/tests.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/filters/query.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/filters/query/tests.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/validation_history.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs",
  "packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc.rs",
  "packages/open-bitcoin-rpc/src/context/filter_index.rs",
  "packages/open-bitcoin-rpc/src/dispatch/filter_index.rs",
  "packages/open-bitcoin-rpc/src/dispatch/filter_index/tests.rs",
  "packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/failures.rs",
  "packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/retention.rs",
  "packages/open-bitcoin-rpc/src/http/filter_index.rs",
  "packages/open-bitcoin-rpc/src/http/tests/filter_index.rs",
  "packages/open-bitcoin-rpc/src/http/tests/filter_index/fixtures.rs",
  "packages/open-bitcoin-rpc/src/method/filter_index.rs",
  "packages/open-bitcoin-rpc/src/method/filter_index/normalize.rs",
  "packages/open-bitcoin-rpc/src/method/filter_index/tests.rs",
  "packages/open-bitcoin-node/src/chainstate.rs",
  "packages/open-bitcoin-node/src/chainstate/fjall_store.rs",
  "packages/open-bitcoin-node/src/lib.rs",
  "packages/open-bitcoin-node/src/network.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/effects.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/filter_index.rs",
  "packages/open-bitcoin-node/src/network/runtime_authority/lifecycle.rs",
  "packages/open-bitcoin-node/src/storage.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/coins.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/filters.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/filters/ownership.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/filters/publication.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/filters/startup.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/filters/tests.rs",
  "packages/open-bitcoin-node/src/storage/fjall_store/payload_usage.rs",
  "packages/open-bitcoin-node/src/sync/runtime_state.rs",
  "packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up.rs",
  "packages/open-bitcoin-rpc/src/bin/open_bitcoind/coins_flush.rs",
  "packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index.rs",
  "packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/fixtures.rs",
  "packages/open-bitcoin-rpc/src/context.rs",
  "packages/open-bitcoin-rpc/src/dispatch.rs",
  "packages/open-bitcoin-rpc/src/error.rs",
  "packages/open-bitcoin-rpc/src/http.rs",
  "packages/open-bitcoin-rpc/src/http/request.rs",
  "packages/open-bitcoin-rpc/src/http/tests.rs",
  "packages/open-bitcoin-rpc/src/method.rs",
  "packages/open-bitcoin-rpc/src/method/tests.rs"
];
/** Fixed nonempty selectors, not inferred from whatever tests happen to remain. */
export const TESTS: [string, string][] = [
  [NODE + "chainstate/validation_history/tests/coverage.rs", "phase159_validation_history_coverage_sparse_raw_metadata_invalidates_without_identity_parse_error"],
  [NODE + "storage/fjall_store/filters/tests/append/admission.rs", "phase159_append_raw_clone_corruption_revokes_proof_and_genuine_recovery_refuses"],
  [CLI + "client/tests.rs", "phase159_filter_rpc_client_blockfilter_envelope_canonicalizes_hash_and_filter"],
  [CLI + "client/tests.rs", "phase159_filter_rpc_client_indexinfo_envelope_preserves_selectors"],
  [CLI + "client/tests.rs", "phase159_filter_rpc_client_filter_method_uses_authenticated_root_endpoint"],
  [CLI + "args/tests.rs", "phase159_filter_rpc_cli_args_accept_positional_named_and_v0"],
  [CLI + "args/tests.rs", "phase159_filter_rpc_cli_args_preserve_index_selectors"],
  [CLI + "args/tests.rs", "phase159_filter_rpc_cli_args_reject_filter_parameter_errors"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_ordinary_fault_retains_live_bounded_fact_and_refuses_absorb"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_before_coins_persistence_failure_is_durable"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_fresh_genesis_forced_flush_keeps_complete_coverage"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_reorg_retains_every_replacement_on_publication_failure"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_equal_and_longer_reorg_retains_displaced_and_every_new_identity"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_reorg_basic_failure_cannot_erase_absorbed_history"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_preview_and_rejected_stage_cannot_mint"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_exact_batch_bound_admitted_one_over_refused_before_absorb"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_missing_filter_and_basic_disable_preserve_retained_acceptance"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_zero_replacement_disconnect_cannot_erase_history"],
  ["packages/open-bitcoin-node/src/storage/validation_history/tests.rs","phase159_validation_history_codec_roundtrip_binds_raw_identity"],
  ["packages/open-bitcoin-node/src/storage/validation_history/tests.rs","phase159_validation_history_codec_rejects_malformed_envelopes"],
  ["packages/open-bitcoin-node/src/storage/validation_history/tests.rs","phase159_validation_history_codec_allows_only_monotonic_same_identity"],
  ["packages/open-bitcoin-node/src/storage/validation_history/tests.rs","phase159_validation_history_codec_coverage_keeps_legacy_absence_unknown"],
  ["packages/open-bitcoin-node/src/storage/validation_history/tests.rs","phase159_validation_history_codec_checks_identity_and_batch_bounds"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests/coverage.rs","phase159_validation_history_coverage_raw_seed_undo_fault_invalidates_before_coins_mutation"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests/coverage.rs","phase159_validation_history_coverage_public_metadata_sink_cannot_preserve_unaccepted_positions"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests/coverage.rs","phase159_validation_history_coverage_successful_raw_seed_retains_only_positive_acceptance"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests/network.rs","phase159_validation_history_accept_network_refusal_precedes_chainstate_preview_and_mempool_patch"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_authority_memory_is_disabled"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_authority_disabled_lifecycle_wins_before_unknown_block"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_authority_corruption_is_typed_and_unknown_resolution_precedes_rows"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_authority_found_during_initial_catch_up_and_legacy_missing"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_authority_captures_unflushed_target_and_summary_processed_latch"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_authority_pending_identity_survives_before_history_commit"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_authority_empty_processed_summary_uses_zero_and_initial_missing_is_prompt"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_measure_continuous_heights_and_legal_singleton"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_before_records"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_before_checkpoint"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_before_protection"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_after_commit"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_corrupt_target"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_corrupt_parent"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_missing_parent"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_missing_accepted_target_preserves_captured_provenance"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_backend_read_is_distinct_from_absence"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_raw_clone_invalidates_final_read"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs","phase159_basic_readiness_capacity_cancellation_and_checked_ids"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs","phase159_basic_readiness_owner_completion_before_poll_has_no_lost_wake"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs","phase159_basic_readiness_owner_original_target_does_not_chase_later_acceptance"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs","phase159_basic_readiness_owner_wrong_hash_token_rejected"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs","phase159_basic_readiness_owner_connected_during_wait_keeps_request_provenance"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs","phase159_basic_readiness_owner_unflushed_completion_and_final_read"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs","phase159_basic_readiness_owner_disable_wakes_and_cancels"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_direct_relay_poison_wakes_before_repoll"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_poisoned_authority_wakes_typed_failure"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_invalid_historical_body_pauses_and_wakes"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_completion_rejects_a_different_authority_incarnation"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_publication_faults_wake_terminal_failure"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_accepted_before_persistence_failure_settles"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_explicit_stop_and_last_handle_drop_settle"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_final_read_rejects_raw_integrity_invalidation"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_reorg_invalidates_exact_branch_and_keeps_latch"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/interleavings.rs","phase159_basic_readiness_owner_direct_dispatch_poison_wakes_outside_guards"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/interleavings.rs","phase159_basic_readiness_owner_waker_reenters_after_both_guards_release"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/interleavings.rs","phase159_basic_readiness_waker_replacement_and_cancel_drop_outside_registry"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/interleavings.rs","phase159_basic_readiness_owner_repoll_uses_latest_waker_once"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/interleavings.rs","phase159_basic_readiness_owner_never_connected_request_keeps_snapshot_after_acceptance"],
  ["packages/open-bitcoin-node/src/sync/runtime_state/tests.rs","phase159_validation_history_store_actual_persist_progress_preserves_trusted_header_coverage_after_reopen"],
  ["packages/open-bitcoin-node/src/sync/runtime_state/tests.rs","phase159_validation_history_store_2000_admitted_headers_are_not_restricted_by_acceptance_batch_cap"],
  ["packages/open-bitcoin-node/src/sync/runtime_state/tests.rs","phase159_validation_history_store_header_publication_fault_stays_closed"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/filters/query/tests.rs","phase159_basic_point_query_requires_recovered_integrity"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/filters/query/tests.rs","phase159_basic_point_query_fixed_target_parent_reads_and_absence"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/filters/query/tests.rs","phase159_basic_point_query_raw_clone_ancestor_mutation_invalidates_every_reader"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/filters/query/tests.rs","phase159_basic_point_query_target_parent_corruption_and_missing_parent_fail_closed"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/filters/query/tests.rs","phase159_basic_query_measure_envelope_and_hex_exact_bound_and_overflow"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/filters/query/tests.rs","phase159_basic_query_measure_codec_maximum_singleton_is_admitted"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs","phase159_validation_history_store_real_reopen_retains_monotonic_history"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs","phase159_validation_history_store_legacy_absence_is_not_backfilled"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs","phase159_validation_history_store_raw_clone_metadata_loses_coverage_not_acceptance"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs","phase159_validation_history_store_rejects_foreign_and_conflicting_batches"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs","phase159_validation_history_store_rejects_conflicting_admitted_batch_before_effects"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs","phase159_validation_history_store_corruption_blocks_exclusive_open_without_basic"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs","phase159_validation_history_store_faults_distinguish_before_and_after_commit"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc.rs","phase159_daemon_rpc_configured_initial_and_exact_shared_results"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc.rs","phase159_daemon_rpc_later_lag_same_owner_and_independent_summary"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc.rs","phase159_daemon_rpc_actual_maintenance_worker_completes_pending_http"],
  ["packages/open-bitcoin-rpc/src/dispatch/filter_index.rs","phase159_filter_rpc_dispatch_disabled_and_summary"],
  ["packages/open-bitcoin-rpc/src/dispatch/filter_index/tests.rs","phase159_filter_rpc_dispatch_exact_missing_matrix"],
  ["packages/open-bitcoin-rpc/src/dispatch/filter_index/tests.rs","phase159_filter_rpc_dispatch_registry_and_node_scope"],
  ["packages/open-bitcoin-rpc/src/dispatch/filter_index/tests.rs","phase159_filter_rpc_dispatch_parameter_precedence_before_disabled"],
  ["packages/open-bitcoin-rpc/src/dispatch/filter_index/tests.rs","phase159_filter_rpc_dispatch_query_faults_are_allowlisted"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/failures.rs","phase159_daemon_rpc_failures_known_header_only_is_never_connected"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/failures.rs","phase159_daemon_rpc_failures_legacy_raw_seed_is_honestly_unknown"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/failures.rs","phase159_daemon_rpc_failures_pending_lifecycle_and_real_append_fence"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/failures.rs","phase159_daemon_rpc_failures_disabled_selection_and_type_precedence"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/failures.rs","phase159_daemon_rpc_failures_configured_auth_cookie_duplicates_and_scope"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/retention.rs","phase159_daemon_rpc_retention_actual_paired_prune_stale_and_all_handle_reopen"],
  ["packages/open-bitcoin-rpc/src/http/filter_index.rs","phase159_filter_rpc_http_raw_duplicates"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_auth_before_parse_and_held_context"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_initial_available_and_index_summary"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_lag_releases_context_summary_and_owner"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_raw_names_syntax_batches_and_notifications"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_exact_precedence_scope_and_versions"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_cookie_success_and_exact_selection"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_waiter_terminal_lifecycle_is_redacted"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_completion_cannot_change_original_hash"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_contract_numeric_errors_roundtrip"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_contract_asymmetric_header_and_filter_projection"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_contract_index_projection_has_exact_basic_fields"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_contract_unmatched_or_disabled_index_is_empty_object"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_contract_filter_selection_and_disabled_diagnostics"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_positional_named_mixed_and_args_agree"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_optional_index_defaults_and_names"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_duplicate_names_win_before_unknown_and_arity"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_unknown_names_and_nonarray_args"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_mixed_collisions_precede_unknown_and_arity"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_named_hole_becomes_required_null_type_error"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_aggregate_types_in_declaration_order"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_type_errors_precede_malformed_hash"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_required_null_is_type_error"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_strict_hash_length_before_filter_selection"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_strict_hash_nonhex_and_no_trim"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_recognized_v0_and_unknown_filter_names"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_wrong_arity_returns_complete_source_derived_help"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/coins_flush.rs","phase159_filter_rpc_maintenance_actual_exit_settles_pending"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/coins_flush.rs","phase159_filter_rpc_maintenance_error_diagnostics_are_redacted"]];
export type Contract = [file: string, symbol: string, anchors: string[]];
/** Fixed minimum action connections; assertions alone cannot replace the test body. */
export const TEST_ACTIONS: [string, string, string][] = [
  [NODE + "chainstate/validation_history/tests/coverage.rs", "phase159_validation_history_coverage_sparse_raw_metadata_invalidates_without_identity_parse_error", "FlushPersistSink::persist_chain_meta"],
  [NODE + "storage/fjall_store/filters/tests/append/admission.rs", "phase159_append_raw_clone_corruption_revokes_proof_and_genuine_recovery_refuses", "write_raw_for_test"],
  [CLI + "client/tests.rs", "phase159_filter_rpc_client_blockfilter_envelope_canonicalizes_hash_and_filter", "build_request_envelope"],
  [CLI + "client/tests.rs", "phase159_filter_rpc_client_indexinfo_envelope_preserves_selectors", "build_request_envelope"],
  [CLI + "client/tests.rs", "phase159_filter_rpc_client_filter_method_uses_authenticated_root_endpoint", "execute_parsed_cli"],
  [CLI + "args/tests.rs", "phase159_filter_rpc_cli_args_accept_positional_named_and_v0", "parse_cli_args"],
  [CLI + "args/tests.rs", "phase159_filter_rpc_cli_args_preserve_index_selectors", "parse_cli_args"],
  [CLI + "args/tests.rs", "phase159_filter_rpc_cli_args_reject_filter_parameter_errors", "parse_cli_args"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_ordinary_fault_retains_live_bounded_fact_and_refuses_absorb","accept"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_before_coins_persistence_failure_is_durable","accept"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_fresh_genesis_forced_flush_keeps_complete_coverage","accept"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_reorg_retains_every_replacement_on_publication_failure","reorg"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_equal_and_longer_reorg_retains_displaced_and_every_new_identity","reorg"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_reorg_basic_failure_cannot_erase_absorbed_history","reorg"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_preview_and_rejected_stage_cannot_mint","validation_provenance"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_exact_batch_bound_admitted_one_over_refused_before_absorb","accept"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_missing_filter_and_basic_disable_preserve_retained_acceptance","validation_provenance"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests.rs","phase159_validation_history_accept_zero_replacement_disconnect_cannot_erase_history","accept"],
  ["packages/open-bitcoin-node/src/storage/validation_history/tests.rs","phase159_validation_history_codec_roundtrip_binds_raw_identity","decode_record"],
  ["packages/open-bitcoin-node/src/storage/validation_history/tests.rs","phase159_validation_history_codec_rejects_malformed_envelopes","encode_record"],
  ["packages/open-bitcoin-node/src/storage/validation_history/tests.rs","phase159_validation_history_codec_allows_only_monotonic_same_identity","BlockValidationIdentity::new"],
  ["packages/open-bitcoin-node/src/storage/validation_history/tests.rs","phase159_validation_history_codec_coverage_keeps_legacy_absence_unknown","decode_coverage"],
  ["packages/open-bitcoin-node/src/storage/validation_history/tests.rs","phase159_validation_history_codec_checks_identity_and_batch_bounds","BlockValidationIdentity::new"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests/coverage.rs","phase159_validation_history_coverage_raw_seed_undo_fault_invalidates_before_coins_mutation","accept"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests/coverage.rs","phase159_validation_history_coverage_public_metadata_sink_cannot_preserve_unaccepted_positions","accept"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests/coverage.rs","phase159_validation_history_coverage_successful_raw_seed_retains_only_positive_acceptance","accept"],
  ["packages/open-bitcoin-node/src/chainstate/validation_history/tests/network.rs","phase159_validation_history_accept_network_refusal_precedes_chainstate_preview_and_mempool_patch","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_authority_memory_is_disabled","basic_filter_query"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_authority_disabled_lifecycle_wins_before_unknown_block","basic_filter_query"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_authority_corruption_is_typed_and_unknown_resolution_precedes_rows","basic_filter_query"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_authority_found_during_initial_catch_up_and_legacy_missing","basic_filter_query"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_authority_captures_unflushed_target_and_summary_processed_latch","maybe_basic_index_summary"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_authority_pending_identity_survives_before_history_commit","connect_local_block"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_authority_empty_processed_summary_uses_zero_and_initial_missing_is_prompt","connect_local_block"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/query/tests.rs","phase159_basic_query_measure_continuous_heights_and_legal_singleton","measure_basic_filter_query_for_test"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_before_records","publication"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_before_checkpoint","publication"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_before_protection","publication"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_after_commit","publication"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_corrupt_target","row_fault"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_corrupt_parent","row_fault"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_missing_parent","row_fault"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_missing_accepted_target_preserves_captured_provenance","basic_filter_query"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_backend_read_is_distinct_from_absence","drive_basic_filter_index_turn"],
  ["packages/open-bitcoin-node/src/sync/tests/filter_index/catch_up/rpc_faults.rs","phase159_rpc_owner_faults_raw_clone_invalidates_final_read","basic_filter_query"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs","phase159_basic_readiness_capacity_cancellation_and_checked_ids","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs","phase159_basic_readiness_owner_completion_before_poll_has_no_lost_wake","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs","phase159_basic_readiness_owner_original_target_does_not_chase_later_acceptance","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs","phase159_basic_readiness_owner_wrong_hash_token_rejected","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs","phase159_basic_readiness_owner_connected_during_wait_keeps_request_provenance","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs","phase159_basic_readiness_owner_unflushed_completion_and_final_read","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests.rs","phase159_basic_readiness_owner_disable_wakes_and_cancels","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_direct_relay_poison_wakes_before_repoll","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_poisoned_authority_wakes_typed_failure","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_invalid_historical_body_pauses_and_wakes","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_completion_rejects_a_different_authority_incarnation","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_publication_faults_wake_terminal_failure","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_accepted_before_persistence_failure_settles","connect_local_block"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_explicit_stop_and_last_handle_drop_settle","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_final_read_rejects_raw_integrity_invalidation","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/failures.rs","phase159_basic_readiness_owner_reorg_invalidates_exact_branch_and_keeps_latch","maybe_basic_index_summary"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/interleavings.rs","phase159_basic_readiness_owner_direct_dispatch_poison_wakes_outside_guards","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/interleavings.rs","phase159_basic_readiness_owner_waker_reenters_after_both_guards_release","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/interleavings.rs","phase159_basic_readiness_waker_replacement_and_cancel_drop_outside_registry","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/interleavings.rs","phase159_basic_readiness_owner_repoll_uses_latest_waker_once","accept"],
  ["packages/open-bitcoin-node/src/network/runtime_authority/filter_index/readiness/tests/interleavings.rs","phase159_basic_readiness_owner_never_connected_request_keeps_snapshot_after_acceptance","accept"],
  ["packages/open-bitcoin-node/src/sync/runtime_state/tests.rs","phase159_validation_history_store_actual_persist_progress_preserves_trusted_header_coverage_after_reopen","persist_progress"],
  ["packages/open-bitcoin-node/src/sync/runtime_state/tests.rs","phase159_validation_history_store_2000_admitted_headers_are_not_restricted_by_acceptance_batch_cap","persist_progress"],
  ["packages/open-bitcoin-node/src/sync/runtime_state/tests.rs","phase159_validation_history_store_header_publication_fault_stays_closed","persist_progress"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/filters/query/tests.rs","phase159_basic_point_query_requires_recovered_integrity","maybe_basic_filter_point_query"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/filters/query/tests.rs","phase159_basic_point_query_fixed_target_parent_reads_and_absence","maybe_basic_filter_point_query"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/filters/query/tests.rs","phase159_basic_point_query_raw_clone_ancestor_mutation_invalidates_every_reader","write_raw_for_test"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/filters/query/tests.rs","phase159_basic_point_query_target_parent_corruption_and_missing_parent_fail_closed","maybe_basic_filter_point_query"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/filters/query/tests.rs","phase159_basic_query_measure_envelope_and_hex_exact_bound_and_overflow","check_envelope"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/filters/query/tests.rs","phase159_basic_query_measure_codec_maximum_singleton_is_admitted","write_raw_for_test"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs","phase159_validation_history_store_real_reopen_retains_monotonic_history","BlockValidationIdentity::new"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs","phase159_validation_history_store_legacy_absence_is_not_backfilled","write_raw_for_test"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs","phase159_validation_history_store_raw_clone_metadata_loses_coverage_not_acceptance","BlockValidationIdentity::new"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs","phase159_validation_history_store_rejects_foreign_and_conflicting_batches","BlockValidationIdentity::new"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs","phase159_validation_history_store_rejects_conflicting_admitted_batch_before_effects","BlockValidationIdentity::new"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs","phase159_validation_history_store_corruption_blocks_exclusive_open_without_basic","write_raw_for_test"],
  ["packages/open-bitcoin-node/src/storage/fjall_store/validation_history/tests.rs","phase159_validation_history_store_faults_distinguish_before_and_after_commit","BlockValidationIdentity::new"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc.rs","phase159_daemon_rpc_configured_initial_and_exact_shared_results","filter"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc.rs","phase159_daemon_rpc_later_lag_same_owner_and_independent_summary","handle_http_request"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc.rs","phase159_daemon_rpc_actual_maintenance_worker_completes_pending_http","handle_http_request"],
  ["packages/open-bitcoin-rpc/src/dispatch/filter_index.rs","phase159_filter_rpc_dispatch_disabled_and_summary","normalize_method_call"],
  ["packages/open-bitcoin-rpc/src/dispatch/filter_index/tests.rs","phase159_filter_rpc_dispatch_exact_missing_matrix","missing_failure"],
  ["packages/open-bitcoin-rpc/src/dispatch/filter_index/tests.rs","phase159_filter_rpc_dispatch_registry_and_node_scope","SupportedMethod::from_name"],
  ["packages/open-bitcoin-rpc/src/dispatch/filter_index/tests.rs","phase159_filter_rpc_dispatch_parameter_precedence_before_disabled","normalize_method_call"],
  ["packages/open-bitcoin-rpc/src/dispatch/filter_index/tests.rs","phase159_filter_rpc_dispatch_query_faults_are_allowlisted","query_failure"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/failures.rs","phase159_daemon_rpc_failures_known_header_only_is_never_connected","filter"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/failures.rs","phase159_daemon_rpc_failures_legacy_raw_seed_is_honestly_unknown","filter"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/failures.rs","phase159_daemon_rpc_failures_pending_lifecycle_and_real_append_fence","handle_http_request"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/failures.rs","phase159_daemon_rpc_failures_disabled_selection_and_type_precedence","invoke"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/failures.rs","phase159_daemon_rpc_failures_configured_auth_cookie_duplicates_and_scope","handle_http_request"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/tests/filter_index/rpc/retention.rs","phase159_daemon_rpc_retention_actual_paired_prune_stale_and_all_handle_reopen","filter"],
  ["packages/open-bitcoin-rpc/src/http/filter_index.rs","phase159_filter_rpc_http_raw_duplicates","handle_http_request"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_auth_before_parse_and_held_context","handle_http_request"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_initial_available_and_index_summary","invoke"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_lag_releases_context_summary_and_owner","handle_http_request"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_raw_names_syntax_batches_and_notifications","handle_http_request"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_exact_precedence_scope_and_versions","handle_http_request"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_cookie_success_and_exact_selection","handle_http_request"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_waiter_terminal_lifecycle_is_redacted","handle_http_request"],
  ["packages/open-bitcoin-rpc/src/http/tests/filter_index.rs","phase159_filter_rpc_http_completion_cannot_change_original_hash","drive_basic_filter_index_turn"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_contract_numeric_errors_roundtrip","serde_json::to_value"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_contract_asymmetric_header_and_filter_projection","GetBlockFilterResult::from_encoded"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_contract_index_projection_has_exact_basic_fields","serde_json::to_value"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_contract_unmatched_or_disabled_index_is_empty_object","serde_json::to_value"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_contract_filter_selection_and_disabled_diagnostics","BlockFilterSelection::parse"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_positional_named_mixed_and_args_agree","normalize_getblockfilter"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_optional_index_defaults_and_names","normalize_getindexinfo"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_duplicate_names_win_before_unknown_and_arity","normalize_getblockfilter"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_unknown_names_and_nonarray_args","normalize_getblockfilter"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_mixed_collisions_precede_unknown_and_arity","normalize_getblockfilter"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_named_hole_becomes_required_null_type_error","normalize_getblockfilter"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_aggregate_types_in_declaration_order","normalize_getblockfilter"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_type_errors_precede_malformed_hash","normalize_getblockfilter"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_required_null_is_type_error","normalize_getblockfilter"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_strict_hash_length_before_filter_selection","normalize_getblockfilter"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_strict_hash_nonhex_and_no_trim","normalize_getblockfilter"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_recognized_v0_and_unknown_filter_names","normalize_getblockfilter"],
  ["packages/open-bitcoin-rpc/src/method/filter_index/tests.rs","phase159_filter_rpc_normalize_wrong_arity_returns_complete_source_derived_help","normalize_getblockfilter"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/coins_flush.rs","phase159_filter_rpc_maintenance_actual_exit_settles_pending","connect_local_block"],
  ["packages/open-bitcoin-rpc/src/bin/open_bitcoind/coins_flush.rs","phase159_filter_rpc_maintenance_error_diagnostics_are_redacted","CoinsFlushError::BasicFilter"],
];
const N = NODE, R = RPC, C = CLI;
export const CONTRACTS: Contract[] = [
  [C+"main.rs", "main", ["env::args_os()", "client::run_cli(&cli_args, &stdin, &default_data_dir())"]],
  [C+"client.rs", "run_cli", ["parse_cli_args(cli_args, stdin)", "resolve_startup_config(", "execute_parsed_cli(&parsed, &startup)"]],
  [C+"client.rs", "canonical_params", ["SupportedMethod::from_name(method_name)", "normalize_method_call(method_name, params)", "method_call_to_json(call)"]],
  [C+"client.rs", "method_call_to_json", ["MethodCall::GetBlockFilter(request)", ".block_hash.as_bytes().iter().rev()", ".collect::<String>()", "match request.filter_type", "BlockFilterSelection::Basic", "BlockFilterSelection::V0", "Ok(serde_json::json!(", "blockhash", "filtertype", "MethodCall::GetIndexInfo(request)", "match request.maybe_index_name", "Some(name) => serde_json::json!(", "name", "None => serde_json::json!({})"]],
  [C+"client.rs", "call_method", ["build_request_envelope(method_name, params, 1)?", "SupportedMethod::from_name(method_name)", ".map(SupportedMethod::scope)", "self.post_json(scope, &request)?", "extract_result(response)"]],
  [C+"client.rs", "post_json", ["self.endpoint_for_scope(scope)", ".post(endpoint_url)", ".header(", "&self.authorization_header", ".send_json(body)"]],
  [C+"client.rs", "endpoint_for_scope", ["scope == MethodScope::Wallet", "self.maybe_wallet_endpoint_url.as_deref()", "return (endpoint_url, endpoint_display)", "(&self.root_endpoint_url, &self.root_endpoint_display)"]],
  [C+"args.rs", "parse_cli_args", ["parse_named_parameters(", "request_parameters_from_positional(", "validate_supported_method(method, &params)?", "CliCommand::RpcMethod("]],
  [C+"args.rs", "validate_supported_method", ["SupportedMethod::from_name(method)", "normalize_method_call(method, params.clone())", ".map_err(map_rpc_failure)"]],
  [R+"method/filter_index/normalize.rs", "normalize_getblockfilter", ["framework_arguments(", "GETBLOCKFILTER_HELP", "parse_hash(hash)?", "BlockFilterSelection::parse(filter_name)?"]],
  [R+"method/filter_index/normalize.rs", "framework_arguments", ["transform_named(named, names)?", "if values.len() < required || values.len() > names.len()", "RpcErrorCode::MiscError", "let mismatches = names.iter().enumerate().filter_map(", "index >= required && value.is_null()", ".collect::<Vec<_>>()", "if !mismatches.is_empty()", "RpcErrorCode::TypeError"]],
  [R+"method/filter_index/normalize.rs", "transform_named", ["arguments.insert(name.clone(), value).is_some()", "maybe_first_named.get_or_insert(", "values.resize(index, Value::Null)", "positional.len() > index", "combined.extend(values.into_iter().skip(combined.len()))", "arguments.keys().next()"]],
  [R+"method/filter_index/normalize.rs", "parse_hash", ["hash.len() != 64", "raw.iter_mut().rev().zip(hash.as_bytes().chunks_exact(2))", "maybe_hex_nibble(pair[0])", "maybe_hex_nibble(pair[1])", "BlockHash::from_byte_array(raw)"]],
  [R+"method/filter_index.rs", "from_encoded", ["filter: lowercase_hex(encoded_filter.iter().copied())", "header: lowercase_hex(raw_header.into_iter().rev())"]],
  [N+"storage/fjall_store/validation_history.rs", "publish_validation_history", ["!accepted.belongs_to(self)", "accepted.validate()?", "self.publish_history_identities(accepted.identities(), StoredValidationStatus::ScriptsValid)"]],
  [N+"storage/fjall_store/validation_history.rs", "publish_history_identities", ["self.filter_publication_guard()?", "self.history_guard()?", "StoredValidationStatus::KnownOnly && coverage != ValidationCoverage::Complete", "FjallPersistMode::SyncAll", "codec::validate_upgrade(", "codec::encode_record(next)", "batch.commit()", "control.poisoned = true"]],
  [N+"storage/fjall_store/validation_history.rs", "check_validation_coverage_for_metadata", ["self.history_guard()?", "!positions.is_empty()", "self.maybe_validation_history_record(position.block_hash)?", "let identity = record.identity()", "record.status() != StoredValidationStatus::ScriptsValid", "identity.hash() != position.block_hash", "identity.parent_hash() != position.previous_block_hash()", "identity.height() != position.height", "authenticated = false", "drop(control)", "if !authenticated", "self.invalidate_validation_coverage()?"]],
  [R+"context/filter_index.rs", "basic_filter_network_handle", ["self.network.clone()"]],
  [R+"method.rs", "normalize_method_call", ["SupportedMethod::GetBlockFilter", "normalize_getblockfilter(params).map(MethodCall::GetBlockFilter)", "SupportedMethod::GetIndexInfo", "normalize_getindexinfo(params).map(MethodCall::GetIndexInfo)"]],
  [R+"dispatch.rs", "dispatch", ["MethodCall::GetBlockFilter(request)", "filter_index::prepare_filter(context, request)", "MethodCall::GetIndexInfo(request)", "filter_index::index_info(context, request)"]],
  [R+"dispatch/filter_index.rs", "prepare_filter", ["request.filter_type == BlockFilterSelection::V0", "return Err(request.filter_type.disabled_failure())", "context.basic_filter_network_handle().basic_filter_query(request.block_hash)", ".map_err(query_failure)?", "project_query(request, query)"]],
  [R+"dispatch/filter_index.rs", "project_query", ["BasicFilterQuery::Missing", "missing_failure(provenance, initially_synchronized)", "BasicFilterQuery::Found(record)", "GetBlockFilterResult::from_encoded(", "record.encoded_bytes()", "*record.filter_header().as_bytes()", "BasicFilterQuery::Pending(barrier)", "PreparedDispatch::Pending { request, barrier }"]],
  [R+"dispatch/filter_index.rs", "missing_failure", ["BasicBlockValidationProvenance::NeverConnected", "RpcErrorCode::InvalidAddressOrKey", "BasicBlockValidationProvenance::ScriptsValid if !initially_synchronized", "RpcErrorCode::MiscError", "BasicBlockValidationProvenance::ScriptsValid", "RpcErrorCode::InternalError", "BasicBlockValidationProvenance::UnknownLegacy => internal_failure()"]],
  [R+"dispatch/filter_index.rs", "index_info", ["maybe_index_name", "BASIC_FILTER_INDEX_NAME", "return Ok(", "context.basic_filter_network_handle().maybe_basic_index_summary()", "synced: summary.synced", "best_block_height: summary.best_block_height", "request.project_basic(maybe_summary)"]],
  [R+"http.rs", "handle_http_request", ["if !authorized(headers, &state.auth)", "return unauthorized_response()", "serde_json::from_slice::<filter_index::ScopedRequest>(body)", "handle_single_request"]],
  [R+"http.rs", "execute_request", ["normalize_method_call(", "state.context.lock().await", "validate_scope(", "prepare(&mut context, call)", "let network = context.basic_filter_network_handle()", "context.clear_request_wallet_name()", "drop(context)", "filter_index::finish(&state.context, network, prepared).await"]],
  [R+"http/filter_index.rs", "finish", ["PreparedDispatch::Pending { request, barrier }", "let completion = barrier.await.map_err(dispatch::query_failure)?", "context.lock().await", "super::validate_scope(", "network.complete_basic_filter_read(request.block_hash, completion)", "dispatch::project_query(request, query)"]],
  [N+"chainstate.rs", "prepare_connect_block_with_current_time", ["self.chainstate.stage_connect_block_with_current_time(", "self.admit_validation_acceptance(", "Ok(PreparedChainstateConnect"]],
  [N+"chainstate.rs", "prepare_reorg", ["self.chainstate.stage_reorg(", "self.prepare_validation_reorg(&staged)?", "prepare_basic_index_reorg(", "Ok(PreparedChainstateReorg"]],
  [N+"chainstate/validation_history.rs", "admit_validation_acceptance", ["self.check_validation_acceptance_available()", "validate_batch_size(positions.len())", "BlockValidationIdentity::new(", "Ok(Some(PreparedValidationAcceptance"]],
  [N+"chainstate/validation_history.rs", "commit_prepared_connect", ["self.check_validation_acceptance_available()", "self.chainstate.absorb_staged_connect(prepared.staged)", "self.observe_absorbed_validation(", "history.seal_connect(&position)", "self.publish_pending_validation_history()", "self.persist()"]],
  [N+"chainstate/validation_history.rs", "commit_prepared_reorg", ["self.check_validation_acceptance_available()", "self.check_basic_index_reorg(", "absorb_staged_reorg_with_receipt(prepared.staged)", "self.observe_absorbed_validation(", "history.seal_reorg(&accepted, &transition)", "let history_result = self.publish_pending_validation_history()", "self.accept_basic_index_reorg(accepted, prepared.maybe_index)", "if let Err(error) = history_result", "self.persist()"]],
  [N+"chainstate/validation_history.rs", "seal_reorg", ["accepted.maybe_old_endpoint()", "accepted.maybe_common_ancestor_endpoint()", "accepted.maybe_new_endpoint()", "self.identities.len() == transition.connected.len()", ".zip(&transition.connected)", "id.hash() == position.block_hash", "id.height() == position.height", "id.parent_hash() == position.previous_block_hash()"]],
  [N+"chainstate/validation_history.rs", "validation_provenance", ["maybe_pending_validation", "pending.identities()", "ValidationProvenance::ScriptsValid", "store.validation_provenance(hash)", "ValidationProvenance::UnknownLegacy"]],
  [N+"storage/fjall_store/coins.rs", "seed_coins_from_snapshot", ["self.filter_publication_guard()?", "self.invalidate_validation_coverage()?", "control.invalidate_append()?", "self.write_migrated_coins_with_tip(", "self.save_undo(", "self.save_unverified_chain_meta("]],
  [N+"storage/fjall_store/coins.rs", "save_validated_chain_meta", ["self.filter_publication_guard()?", "self.check_validation_coverage_for_metadata(active_chain)?", "control.invalidate_append()?", "control.chain_meta_fault()?", "self.coins_view()"]],
  [N+"network/runtime_authority/filter_index/query.rs", "query_network", ["maybe_basic_filter_query_store()", "if !reader.enabled", "maybe_pending_validation_identity(hash)", "header_store().entry(&hash)", "store.maybe_validation_history_record(hash)", "BasicFilterQuery::UnknownBlock", "progress.initially_synchronized()", "QueryStage::Pending(", "provenance", "reader.maybe_record(hash)?", "chainstate.validation_provenance(hash)?", "readiness.register("]],
  [N+"network/runtime_authority/filter_index/query.rs", "maybe_basic_index_summary", ["self.read(", "store.with_basic_filter_query(", "progress.initially_synchronized()", "progress.maybe_processed_endpoint()", ".map_or(0, |record| record.height())"]],
  [N+"storage/fjall_store/filters/query.rs", "basic_filter_point_query_guarded", ["control.read_integrity", "codec::record_key(hash)", "check_envelope(bytes.len())?", "checked_response_hex_bytes(encoded_len)?", "charge_hash_work(&mut work, encoded_len, true)?", "codec::parse_record(&key, &bytes)?", "codec::record_key(target.parent)", "check_envelope(parent_bytes.len())?", "*size <= BASIC_FILTER_QUERY_MAX_READ_BYTES", "charge_hash_work(&mut work, parent_len, false)?", "codec::parse_record(&parent_key, &parent_bytes)?", "target.verify_parent(Some(&parent))?", "target.checkpoint_identity(Some(&parent))?", "bytes: encoded.to_vec()"]],
  [N+"network/runtime_authority/filter_index/readiness.rs", "register", ["registry.waiters.len() >= MAX_BASIC_FILTER_WAITERS", "BasicFilterReadFailure::Capacity", ".checked_add(1)", "BasicFilterReadFailure::CounterExhausted", "registry.waiters.insert(", "BasicFilterReadBarrier {", "frontier", "request"]],
  [N+"network/runtime_authority/filter_index/readiness/owner.rs", "maybe_frontier_result", ["network.authority_epoch.raw() != frontier.authority_incarnation()", "progress.generation() != frontier.generation()", "progress.branch_identity() != frontier.branch_identity()", "frontier.accepted_hash()", "manager.has_pending_validation_history()", "record.height() >= frontier.accepted_height()"]],
  [N+"network/runtime_authority/filter_index/readiness/owner.rs", "complete_basic_filter_read", ["hash != completion.request.hash", "maybe_frontier_result(network, completion.frontier)", "reader.matches_generation(completion.frontier.generation())", "reader.maybe_record(hash)?", "record.identity().height() != completion.request.height", "record.identity().parent_hash() != completion.request.parent", "provenance: completion.request.provenance"]],
  [N+"network/runtime_authority/filter_index/readiness/owner.rs", "lock_authority", ["self.authority.lock().map_err(", "drop(poison.into_inner())", "self.basic_filter_authority_unavailable()"]],
  [N+"network/runtime_authority/filter_index/readiness/owner.rs", "mutate", ["self.lock_authority()?", "command(&mut network)", "self.collect_basic_filter_wakes(&network)", "drop(network)", "wake_all(wakes)"]],
  [N+"network/runtime_authority/filter_index/readiness/owner.rs", "stop_basic_filter_readiness", ["self.lock_authority()?", "self.basic_filter_readiness.stop()", "drop(network)", "wake_all(wakes)"]],
  [R+"bin/open_bitcoind/coins_flush.rs", "coins_flush_worker_loop", ["handle.stop_basic_filter_readiness()", "handle.stop_basic_filter_readiness()"]],
];
export const TEST_CONTRACTS: Contract[] = [
  [N+"chainstate/validation_history/tests/coverage.rs", "phase159_validation_history_coverage_sparse_raw_metadata_invalidates_without_identity_parse_error", ["for matching_hash in [false, true]", "accept(&mut manager, &accepted, 0)", "ChainPosition::new(raw.header, 50, 50, 1_700_000_000)", "BlockValidationIdentity::new(", ".is_err()", "FlushPersistSink::persist_chain_meta(", "store.load_chain_meta_for_open()", "recovered_validation_history()", "ValidationProvenance::ScriptsValid", "ValidationProvenance::UnknownLegacy", "drop(manager)", "drop(store)", "FjallNodeStore::open(&dir)", "ValidationProvenance::ScriptsValid", "ValidationProvenance::UnknownLegacy"]],
  [N+"storage/fjall_store/filters/tests/append.rs", "recovered", ["seed(store, positions)", "save_block(", "if position.height != 0", "save_undo(", "configure_basic_filter_index_before_prune(", "BasicFilterStartupMode::Enabled"]],
  [N+"storage/fjall_store/filters/tests/append/admission.rs", "phase159_append_raw_clone_corruption_revokes_proof_and_genuine_recovery_refuses", ["recovered(&store, &positions)", "append(&store, &records[..2])", "maybe_basic_filter_append_proof_with_budget(budget())", "write_raw_for_test(", "check_basic_filter_append_proof(&proof)", "expect_err(", "maybe_basic_filter_append_proof_with_budget(budget())", "is_none()", "configure_basic_filter_index_before_prune(", "BasicFilterStartupMode::Enabled", "expect_err(", "Some(bytes)"]],
  [C+"client/tests.rs", "phase159_filter_rpc_client_blockfilter_envelope_canonicalizes_hash_and_filter", ["RequestParameters::Positional", "hash.to_uppercase()", "RequestParameters::Named", "RequestParameters::Mixed", "super::build_request_envelope(", "serde_json::to_value(request)"]],
  [C+"client/tests.rs", "phase159_filter_rpc_client_indexinfo_envelope_preserves_selectors", ["RequestParameters::None", "RequestParameters::Positional", "RequestParameters::Named", "super::build_request_envelope(", "serde_json::to_value(request)"]],
  [C+"client/tests.rs", "phase159_filter_rpc_client_filter_method_uses_authenticated_root_endpoint", ["TestServer::start(", "parse_cli_args(", "RpcAuthConfig::UserPassword", "execute_parsed_cli(&parsed, &startup)", "serde_json::from_str::<serde_json::Value>(&output)", "server.requests()", "CapturedRequest", "authorization: Some("]],
  [C+"args/tests.rs", "phase159_filter_rpc_cli_args_accept_positional_named_and_v0", ["BlockFilterSelection::Basic", "BlockFilterSelection::V0", "parse_cli_args(&args,", "MethodCall::GetBlockFilter(request)", "normalize_method_call(&command.method, command.params)", "assert_eq!(request.filter_type, expected_filter)"]],
  [C+"args/tests.rs", "phase159_filter_rpc_cli_args_preserve_index_selectors", ["RequestParameters::None", "RequestParameters::Positional", "RequestParameters::Named", "parse_cli_args(&args,", "assert_eq!(parsed.command,", "params: expected_params"]],
  [C+"args/tests.rs", "phase159_filter_rpc_cli_args_reject_filter_parameter_errors", ["for (args, expected_error) in cases", "assert_eq!(parse_cli_args(&args,", ".expect_err(", ".to_string()", "expected_error"]],
  [R+"method/filter_index/tests.rs", "phase159_filter_rpc_contract_numeric_errors_roundtrip", ["RpcErrorCode::TypeError", "RpcErrorCode::InvalidAddressOrKey", "code.as_i32()", "serde_json::to_value(code)", "serde_json::from_value::<RpcErrorCode>(json!(number))"]],
  ...["BeforeRecords", "BeforeCheckpoint", "BeforeProtection", "AfterCommit"].map((fault, index) => [N+"sync/tests/filter_index/catch_up/rpc_faults.rs", "phase159_rpc_owner_faults_"+["before_records", "before_checkpoint", "before_protection", "after_commit"][index], ["publication(FilterPublicationFault::"+fault+")"]] as Contract),
  ...["CorruptTarget", "CorruptParent", "MissingParent"].map((fault, index) => [N+"sync/tests/filter_index/catch_up/rpc_faults.rs", "phase159_rpc_owner_faults_"+["corrupt_target", "corrupt_parent", "missing_parent"][index], ["row_fault(QueryRecordFault::"+fault+")"]] as Contract),
  [R+"bin/open_bitcoind/tests/filter_index/rpc/retention.rs", "phase159_daemon_rpc_retention_actual_paired_prune_stale_and_all_handle_reopen", ["DaemonFixture::new(401)", "PruneMode::ManualOnly", "height_inside_keep_window(400, 20)", "flush_applying_prune_plan(", "heights: vec![20]", "assert_eq!(deletion.deleted_block_hashes, vec![pruned])", "fixture.store.load_block(pruned)", "fixture.store.load_undo(pruned)", "assert!(after < before)", "fixture.accept_next()", "replace_tip(&mut fixture, 390, 11)", "assert_eq!(filter(&fixture, stale).await, original_stale)", "drop(snapshot)", "FjallNodeStore::open(&fixture.path).is_err()", "fixture.close()", "DaemonFixture::open(path, blocks, true)", "assert_eq!(filter(&fixture, pruned).await, original_pruned)", "assert_eq!(filter(&fixture, stale).await, original_stale)", "assert_eq!(filter(&fixture, active).await, original_active)", "fixture.store.load_block(pruned)", "fixture.store.load_undo(pruned)"]],
  [N+"sync/tests/filter_index/catch_up/rpc_faults.rs", "genuine", ["FjallNodeStore::open(", ".connect_local_block(block, ScriptVerifyFlags::P2SH, params())", ".flush_coins(", "is_complete()", "drop(runtime)", "DurableSyncRuntime::open_configured(", ".connect_local_block(&history.blocks[2]", "ValidationProvenance::ScriptsValid"]],
  [N+"sync/tests/filter_index/catch_up/rpc_faults.rs", "publication", ["genuine()", "BasicFilterQuery::Pending", ".basic_filter_query(hash)", "is_pending()", "set_basic_filter_fault(fault)", "drive_basic_filter_index_turn().is_err()", "BasicFilterReadFailure::OwnerFailed", "ValidationProvenance::ScriptsValid"]],
  [N+"sync/tests/filter_index/catch_up/rpc_faults.rs", "row_fault", ["genuine()", "drive_basic_filter_index_turn()", "BasicFilterQuery::Found", ".inject_query_record_fault_for_test(hash, fault)", "runtime.network.basic_filter_query(hash)", "StorageError::Corruption", "ValidationProvenance::ScriptsValid", "drop(runtime)", "DurableSyncRuntime::open_configured(", "is_err()"]],
  [N+"sync/tests/filter_index/catch_up/rpc_faults.rs", "phase159_rpc_owner_faults_backend_read_is_distinct_from_absence", ["genuine()", "FilterPublicationFault::BeforeQueryRead", "basic_filter_query(hash)", "StorageError::BackendFailure", "ValidationProvenance::ScriptsValid"]],
];
